## About the book {-}

*On The Line* tells the story of schooling and housing boundaries that shaped American metropolitan life over the past century, and also the civil rights struggles of families and activists to cross over, redraw, or erase these powerful lines. Set in the city of Hartford, Connecticut, and its emerging suburbs, the book explains how this metropolitan area became one of the most racially and economically polarized regions in the northeastern United States. The story highlights how government, business, and white middle-class families drew lines to distance themselves from others, and the evolving coalitions that have sought to reform the relationship between private housing and public education.  

This **digital-first book** was designed for the open web. The narrative is wrapped around digital evidence---including interactive maps, videos, and documents---to make hidden boundaries more visible, and to amplify the voices of people who challenged these lines. *On The Line* is best read in your web browser, where readers may fully explore the evidence, follow links to related sources, and connect with the author and other readers through comments. In addition to the web edition, the same text (with static images and links) also appears in the downloadable e-book versions, and an inexpensive print edition to come.  

In an **open-access book**, history becomes more widely available to the public, without barriers of price or permissions. As educators, we believe that knowledge becomes more valuable when it is easily discoverable and accessible, not hidden behind password-protected paywalls. Moreover, the liberating power of history---and civil rights history in particular---should be freely available, especially for the communities of people who lived these stories. Anyone may freely read this book online or download it from the web, and after it is completed, purchase or borrow a low-cost paperback edition.

Written **for the liberal arts**, the book blends interdisciplinary scholarship with highly-engaged student learning. It draws on the fields of history, social sciences, and policy analysis in urban America, and more than a decade of collaborative research with undergraduate students, faculty, staff, and community partners at Trinity College. Rather than simply report our results, we describe our discovery process, so that others may expand upon, or even challenge our findings, in future works. We also strived to explain new concepts and make the text accessible for younger students and residents of the Hartford region.

In sum, *On The Line* blends the best aspects of conventional publishing and web innovation. The main narrative still looks and feels like a scholarly book, divided into chapters and backed up by endnotes. But the web platform allows us to embed digital evidence on the page, and to link directly to external resources located elsewhere. As a result, this book delivers a more comprehensive, coherent, and connected work of scholarship than what was previously possible in print-only publications, or scattered online journal articles and blog posts, at no cost to the reader. Flip the page---in whatever format you prefer---and find out for yourself.  
