## Outline of the Book {- #outline}
*On The Line* seeks to bridge this disciplinary divide by showing how the dynamic relationship between schooling and housing reshaped our cities and suburbs. During the immediate post-war years of mass suburban housing, public schools in many of these formerly rural towns were seen as inferior to the big-city districts, and a deterrent to outward migration. But in the late 1950s and '60s, a convergence of three groups---real estate industry, pro-suburban government, and white middle-class homebuyers---invested in suburban public schools, marketed them to private homes, and defended their attendance boundary lines. This schooling-housing convergence became more powerful in US families' lives in the human capital market of the 1960s to today, when education credentials have become the most reliable means to transfer middle-class privilege to one's children. Americans seeking upward mobility began to embrace what we recognize today as a familiar formula: buy a home in the right neighborhood, in order to send your children to a good school, to increase their odds of being accepted into a top-ranked college, to help them to land the perfect job. Moreover, wealth-based schooling and housing boundaries became a more legitimate way for upper-class white families to defend and pass on their privileges, without resorting to overtly racist boundaries of the past, while still distancing their children from other students perceived to be less desirable peers. America's story of urban decline and suburban ascent, and civil rights struggles to challenge these inequalities, cannot be told without the interaction between two key ingredients--- housing and schooling---and the boundary lines that bind them together.

This book concentrates on the metropolitan Hartford story, and is divided into multiple chapters of narrative and evidence, organized thematically and chronologically to advance key elements of the broader historical argument.

[Chapter 1: Defining City and Suburban Lines](defining.html) begins by challenging us to reconsider the familiar poor cities and rich suburbs narrative that is so ingrained in our present-day thinking. But a century ago, these roles were reversed. Connecticut's capital city was the center of financial wealth, adorned by its crown jewel of public education, Hartford Public High School. Urban schools earned such a strong reputation through the early 1900s that they attracted families from outlying towns to send their children into the city's borders. By contrast, public schools in areas that we consider today to be elite suburbs, were relatively weak rural districts at this time. This part of the book begins to explain the reversal of fortunes between Hartford's city and its suburbs over time. Larger colonial-era tracts of land were carved up into smaller town boundaries, state laws formed more rigid school district lines, and suburban voters blocked urban annexation. Today's Connecticut is highly fragmented into 169 municipal governments, and most manage their own public school districts and land-use decisions, with weak regional governance. Even the phrase "metropolitan Hartford," which appears in this book, has no official nor consistent definition. As a result, self-interested suburban policies with state governmental support have generated some of the nation's highest levels of inequality between the central city and its suburbs, and also across suburbs of different socioeconomic standings.

[Chapter 2: Segregating Along Color Lines](segregating.html) explains how the boundaries of White privilege and racism have shifted over time, from explicit racial barriers to more sophisticated hurdles, across both schooling and housing. The Connecticut legislature banned schooling for out-of-state Black students during the 1830s, and Hartford leaders voted to officially segregate public schools for a brief period in 1868, and proposed it again in 1917. After civil rights activists overturned these policies, Hartford officials quietly continued to separate many Black and White students through its decisions on locating new schools and redrawing attendance lines well into the 1970s. In the housing sector, local and federal governments and lenders strengthened the color line through discriminatory 'redlining' in mortgage lending, enforcing White-only property deeds, and creating White-only public housing. Even after civil rights activists overturned several of these governmental barriers, Connecticut's real estate industry reframed the color line through racial steering and other tactics that were harder to detect, even after the federal Fair Housing Act of 1968 outlawed these and related practices.

[Chapter 3: Excluding Through Zoning Lines](excluding.html) makes this hidden history more visible, and explains how decisions made by local and state governmental leaders shaped the suburban landscape in metropolitan Hartford. In general, *zoning* refers to rules over how land can be used, and some zoning policies have progressive goals, such as separating industrial factories from residential neighborhoods. But in present-day debates, *exclusionary zoning* refers to policies that favor expensive single-family home construction that requires large amounts of property, rather than more affordable multi-family homes that use less land per resident. In Connecticut, the origins of exclusionary zoning can be traced back one suburban town's attempt to block an urban Jewish grocery from building a store in a residential neighborhood in the early 1920s. When the town's effort failed, it sparked a political movement to create stronger legal tools to control future real estate development and exclude types of property (and people) deemed as undesirable neighbors. Exclusionary zoning laws intentionally made it more expensive to build homes in suburban neighborhoods, which effectively limited lower-income people from living there. Unlike other discriminatory barriers of this era---such as [mortgage redlining](lending.html) or [restrictive covenants](restricting.html) or [segregated public housing](public-housing.html)---exclusionary zoning did not directly refer to race, religion, or nationality. Instead, exclusionary zoning cleverly carved up suburban neighborhoods using minimum-land rules that segregated residents by their wealth. In this way, exclusionary zoning became a more sophisticated tool of housing discrimination that largely resisted fair-housing legislation of the 1960s-70s civil rights era, and continues to divide Connecticut into the present day.

[Chapter 4: Selling and Shopping the Lines](selling.html) explores the pivotal relationship between public schooling and private housing, which fundamentally reshaped metropolitan life and upward mobility strategies in Connecticut in the latter half of the twentieth century. By contrast, in the early 1900s, when a smaller proportion of youth pursued secondary education and beyond, most families did not choose their homes based on the boundary lines of desirable public schools. Prior to the 1950s, schools were relatively weak in attracting middle-class families to the suburbs, but in post-war human capital markets, education became a powerful magnet. Pro-suburban government, real estate interests and prospective homebuyers converged to create the practice commonly known today as "shopping for schools." Agents began to advertise private homes by their location in higher status public school areas. Local school leaders competed for upper-class families by offering curricular extras. State legislators invested in suburban schools, and legitimized school-by-school rankings by publishing standardized test results. Upwardly mobile families with children sought more desirable school attendance areas, and paid higher prices for private homes that included access to this public good. Overall, the rise of shopping for schools unites the twin narratives of credentialism and consumerism in American metropolitan history.

[Chapter 5: Crossing and Defending the Lines](crossing.html) tells the stories of everyday families and civil rights activists who sought to cross over schooling and housing boundaries in metropolitan Hartford, and the people and institutions who defended these lines. When comparing these stories, we learn that the tools of privilege do not stand still, but evolve when confronted by civil rights challenges. In turn, this requires newer generations of activists to continually rethink and revise strategies to address the limited successes of prior years. After Connecticut civil rights advocates won legislative bans against overt racial discrimination in public housing in the late 1940s, and most private housing in the 1960s, they needed to create more sophisticated strategies to combat racial steering and redlining practices, since these were more difficult to prove without direct testing and quantitative studies. Similarly, although activists won a 1965 state constitutional amendment for equal public schools, initial efforts to implement this law were equally challenged in moving students or dollars across city-suburban district lines.

[Chapter 6: Blurring the Lines with Choice Policies](blurring.html) explains how despite successful legal challenges, school and housing boundaries remain largely intact in Connecticut, though somewhat blurred by a set of compromises around public school choice and housing voucher policies that allow some, but not all, individuals to cross over these lines. After school integration activists sued Connecticut officials over unconstitutional district boundaries in the *Sheff v O'Neill* case, the state's highest court outlawed the segregation of Hartford's Black and Brown students in 1996, but left the specific remedy to be determined by a suburban-dominated political process. Connecticut's 2003 school integration settlement hinged on voluntary public school choice that did not require participation by any individual, or initially, any suburban district. Instead, state leaders agreed to expand interdistrict magnet schools, with highly-desirable curricular offerings in the arts, sciences, and other specialties to attract white suburban families to voluntarily enroll their children in the same school as urban students of color. The Sheff remedy signals a tangible civil rights victory. As of 2015, state funding for 48 interdistrict magnet schools and the Open Choice city-suburban transfer program enrolls about 12,000 Hartford minority students (or 45 percent of the total) in racially integrated settings. But compromises come at a cost. Interdistrict schools merely blur the boundary lines, rather than erase the root causes of inequality. Furthermore, this voluntary integration plan protects suburban white privilege, and our data analysis shows how it favors more privileged Hartford families. The Sheff remedy has attracted critics from all sides, but the suburban-dominated state government has resisted change and threatened to unilaterally drop all support, despite the judge's order. At present, the Sheff schooling compromise---and related housing voucher policies that promise greater choice---are caught in a standoff, with suburban interests holding the upper hand.

[Conclusion: Where to Draw the Line?](conclusion.html) offers historical reflections on present-day policy decisions *to come*.

Two additional chapters offer readers a behind-the-scenes look into the process of creating this book:

[Teaching and Researching *On The Line*](teaching-researching.html) describes how the book emerged through working with liberal arts undergraduates and Hartford-area community partners in the Cities Suburbs and Schools seminar at Trinity College. For educators, this chapter offers lesson ideas to help students of all ages explore key questions about past and present topics raised in the book. For historical researchers, this chapter describes some of the methods and source materials consulted in creating this book, and some questions that remain unresolved. By making our work process more transparent, we hope to inspire people to educate others and engage in further research on topics in this book.

[Mapping and Publishing *On The Line*](mapping-publishing.html) details our design process and web technologies we used to create this open-access digital book. Our interactive web maps, built with open-source Leaflet code, help broader audiences to visualize spatial and historical change over time. The chapter also describes our publishing workflow, based on the open-source Bookdown package for RStudio, which produces both HTML web pages and PDF print pages. We share our knowledge about these tools so that others may innovate and build more digital books to tell their own stories.
