## Contributors {-}

##### Trinity College undergraduate student researchers and co-authors {-}

Jasmin Agosto (Trinity 2010) co-authored [Mobilizing Against Racial Steering and Redlining](challenging.html#mobilizing-against-racial-steering-and-redlining), and also researched 18th-19th century school documents, and decades of school residency cases.

Richelle Benjamin (Trinity 2015) researched school residency cases and conducted oral history interviews.

Ilya Ilyankou (Trinity 2018) developed several interactive maps in this book. His open-source code and map links are available at our GitHub public repository: <http://github.com/OnTheLine/>.

Vianna Iorio (Trinity 2019) co-authored [Restricting with Property Covenants](separating.html#restricting-with-property-covenants), [Jumping the School District Line](challenging.html#jumping-the-school-district-line), and other chapters TO COME.

Katie Campbell Levasseur (Trinity 2011) conducted restrictive covenant property records research and co-authored [How We Found Restrictive Covenants](creating.html#how-we-found-restrictive-covenants).

JiYun (Lisa) Lee (Trinity 2017) co-authored [Jumping the School District Line](challenging.html#jumping-the-school-district-line).

Shaun McGann (Trinity 2014) co-authored [Federal Lending and Redlining](separating.html#federal-lending-and-redlining).

Candace Simpson (Trinity 2012) conducted oral history interviews on restrictive property covenants and Sheff v. O'Neill.

Tracey M. Wilson (Trinity 1976) co-authored [Restricting with Property Covenants](separating.html#restricting-with-property-covenants).

##### University of Connecticut Libraries MAGIC (Map and Geographic Info Center) {-}

...and MANY MORE TO COME...
