# Defining City and Suburban Lines {#defining}

This chapter begins by challenging us to reconsider the familiar poor cities and rich suburbs narrative that is so ingrained in our present-day thinking. But a century ago, these roles were reversed. Connecticut's capital city was the center of financial wealth, adorned by its crown jewel of public education, Hartford Public High School. Urban schools earned such a strong reputation through the early 1900s that they attracted families from outlying towns to send their children into the city's borders. By contrast, public schools in areas that we consider today to be elite suburbs, were relatively weak rural districts at this time. This part of the book begins to explain the reversal of fortunes between Hartford's city and its suburbs over time. Larger colonial-era tracts of land were carved up into smaller town boundaries, state laws formed more rigid school district lines, and suburban voters blocked urban annexation. Today's Connecticut is highly fragmented into 169 municipal governments, and most manage their own public school districts and land-use decisions, with weak regional governance. Even the phrase "metropolitan Hartford," which appears in this book, has no official nor consistent definition. As a result, self-interested suburban policies with state governmental support have generated some of the nation's highest levels of inequality between the central city and its suburbs, and also across suburbs of different socioeconomic standings.
