# Challenging the Power Lines {#challenging}

This chapter tells the stories of everyday families and civil rights activists who sought to cross over, redraw, or erase schooling and housing boundaries in metropolitan Hartford, focusing primarily on the past five decades. When comparing these stories, we learn that the tools of privilege do not stand still, but evolve when confronted by civil rights challenges. In turn, this requires newer generations of activists to continually rethink and revise strategies to address the limited successes of prior years. After Connecticut civil rights advocates won legislative bans against overt racial discrimination in public housing in the late 1940s, and most private housing in the 1960s, they needed to create more sophisticated strategies to combat racial steering and redlining practices, since these were more difficult to prove without direct testing and quantitative studies. Similarly, although activists won a 1965 state constitutional amendment for equal public schools, initial efforts to implement this law were equally challenged in moving students or dollars across city-suburban district lines. This portion concludes with the 1996 courtroom victory of the *Sheff v O'Neill* school integration plaintiffs, where Connecticut's highest court outlawed the segregation of Hartford minority students, but left the specifics of the remedy to be determined by a suburban-dominated political process.