## Building with Bookdown, GitHub, and Zotero {-}
*by [Jack Dougherty and Ilya Ilyankou](index.html#authors-and-contributors)*

We are building this open-access book with open-source tools---namely Bookdown, GitHub, and Zotero---and openly sharing the knowledge we acquire so that others may improve on the process. We welcome feedback from digitally-minded authors and software developers on [Twitter](https://twitter.com/doughertyjack) or directly on the GitHub repo for this page <https://github.com/OnTheLine/otl-bookdown/blob/master/09.3-bookdown.Rmd>.

- [Bookdown](http://bookdown.org), an open-source software package by Yihui Xie at RStudio, allows authors to compose in version of [Markdown](https://en.wikipedia.org/wiki/Markdown), an easy-to-read-and-write cross-platform syntax, and create one workflow that produces their book in multiple formats: Web edition, PDF edition, ePUB ebook edition, and Microsoft Word. Furthermore, Bookdown generates the Web edition as a set of static-site HTML files, which display digital elements (such as interactive maps and videos) and load very quickly into readers' browsers. Individual authors can install Bookdown on their Mac, Windows, or Linux computers, as it does not require a server. Interestingly, Bookdown requires installing the open-source [R Project](https://www.r-project.org/) and [RStudio console and editor](https://www.rstudio.com/), which typically are used for statistical data analysis. Athough Bookdown may not be the best choice for novice computer users, installation steps are outlined below, along with a recommended workflow for authoring and publishing with GitHub and Zotero.^[For a detailed guide, see @xieBookdownAuthoringBooks2018]
- [GitHub](http://github.com) is an open-source repository that enables us to publicly share the text and code in this book, with a version-control system that allows collaborators to work on different sections at the same time. Also, the [GitHub Pages](http://pages.github.com) feature allows us to freely host online all of the book editions (Web, PDF, etc.), with a custom domain name purchased through another service, [Reclaim Hosting](http://reclaimhosting.com). As this is an open-access publication, we intentionally make its contents public---and also share instructions like this---while we work on the book, which is consistent with the contract signed with our open-access publisher. Note that GitHub also allows users the option to make repositories private.
- [Zotero](http://zotero.org) is an open-source bibliography manager to collect sources and organize citations, created by the Roy Rosenzweig Center for History and New Media at George Mason University. [Better BibTeX](https://github.com/retorquere/zotero-better-bibtex) is an extension by Emiliano Heynes that makes Zotero citation keys work better with Markdown text workflows. While Bookdown does not require using Zotero, scholars who need to manage multiple source materials and citations will benefit from the Bookdown---Zotero---Better BibTeX workflow described below.

#### Alternative Tools and Platforms {-}
Before leaping into any software platform, consider the costs and benefits of using that tool to achieve your goal, such as writing and publishing a web-and-print book like this one.

- Conventional word processors: Most authors work primarily with text, and are content with a traditional book-publishing workflow that begins with composing in Microsoft Word or LibreOffice, then handing it off to a publisher for review, copyediting, layout, and distribution. But this book is designed to blend text and digital media (such as interactive maps, video clips, scanned documents, and links) and publishing the book in two formats: on the public web (for free) and an inexpensive paperback (for sale). Traditional word processors do not achieve this goal.
- Sophisticated word processors: [Scrivener](https://www.literatureandlatte.com/scrivener) by Literature & Latte is a powerful word-processor and outlining tool designed to help authors see both "the forest or the trees" of book-length manuscripts. In fact, the first few chapters of this *On The Line* book were initially composed in Scrivener. Although Scrivener supports a different version of Markdown, the tool was not designed to integrate interactive maps and charts into text, nor does it support multi-author collaboration or sharing files on a public repository.
- Cloud-based word processors: Some authors realize the benefits of writing collaboratively or sharing drafts in public or semi-public venues for early feedback. One way to attain these benefits with little investment of technology and time is to compose chapters of a book in [Google Documents](http://docs.google.com) or similar cloud-based word-processors. In fact, some text of chapters for this book were collaboratively composed and edited in Google Docs, then converted to Markdown format using a Google add-on tool, [Docs to Markdown](https://chrome.google.com/webstore/detail/docs-to-markdown/igffnbdfnodiaphfmfaiiaegmoljbghf?utm_source=permalink) by ed.bacher, and migrated to Bookdown. Although Google Documents can display static images of interactive maps and videos, with links to live online versions, it was not designed to publish book-length editions for the web or PDF.
- [WordPress.org](http://wordpress.org) is an open-source web authoring platform, used by over 33 percent of the top 10 million websites as of 2019. Users can create a free account on [WordPress.com](http://wordpress.com), or freely download the WordPress software and run a self-hosted version on a server, which requires developer skills or a third-party service, such as [ReclaimHosting.com](http://reclaimhosting.com). Although WordPress creates web pages, it was not designed to produce PDFs or print books. An earlier version of this *On The Line* book was hosted on a WordPress site from its inception in [2010](https://web.archive.org/web/20100614053219/http://ontheline.trincoll.edu/) until [2014](https://web.archive.org/web/20141229115227/http://ontheline.trincoll.edu/), as shown in these links to the Internet Archive.^[@doughertyLine2010]
- [Pressbooks](http://pressbooks.com) is an open-book publishing platform built on an open-source variation of WordPress Multisite, which produces books in different formats: web, print (PDF), ebooks (ePUB), etc. Authors can pay to publish on the Pressbooks.com platform or a third-party service such as [ReclaimHosting.com](http://reclaimhosting.com), or [freely download the software](https://github.com/pressbooks) to run on a server, which requires developer skills. Although Pressbooks is a powerful tool, it requires an investment of time and resources to install and maintain its platform, dependencies, and updates. Also, creating a book in Pressbooks requires authors to compose directly in the WordPress-style editor, or copy-and-paste content from word processor to web platform. The latter workflow is better for authors who wish to easily see and edit across all of their chapters, but requires continually updating back-and-forth between the word processor and web platform to keep both versions identical. An earlier version of the *On The Line* book-in-progress existed on a self-hosted Pressbooks server at Trinfo.Cafe at Trinity College from [2015](https://web.archive.org/web/20150612122023/http://epress.trincoll.edu/ontheline2015/) until [2017](https://web.archive.org/web/20170712062322/http://ontheline.trincoll.edu/book/), as shown in these links to the Internet Archive. While the digital and print versions looked great, maintaining the self-hosted Pressbooks site was a chore, and continually moving back-and-forth between the word processor and web platform versions was not ideal. Composing in Bookdown was simpler because there was only one version of the book: the word processor and web platform are the same.
- [Scalar](https://scalar.me/) is an open-source scholarly authoring and publishing platform by the Alliance for Networking Visual Culture, with support from the Mellon Foundation and the National Endowment for the Humanities. The platform was created primarily for authors to assemble born-digital book-length works online, with media from multiple sources, and it allows multi-author collaboration. But the platform was not designed to produce PDFs or print books, so was not considered for this book. See examples of online-only works at <https://scalar.me/anvc/scalar/showcase/>. Users can freely register to create works on the Scalar platform hosted by the University of Southern California at <http://scalar.usc.edu/works/>, or
- [Manifold](https://manifoldapp.org) is an open-source scholarly publishing platform created through a collaboration by the University of Minnesota Press, the Graduate Center at the City University of New York, and Cast Iron Coding, with funding from the Mellon Foundation. The platform was designed primarily for authors to integrate digital media into their texts, and also for readers to view and annotate drafts and finished books online. It appears that print book production is handled separately. Since installing Manifold on a server requires developer skills, most authors will submit text and media to be uploaded to a server hosted by a publisher or other organization. For example, see Manifold-produced books on the University of Minneapolis Press server at <https://manifold.umn.edu>. Since the Manifold platform can ingest texts written in Markdown, Microsoft Word, and other formats, it should be feasible to upload a manuscript that was originally produced in Bookdown.
- [Fulcrum](https://www.fulcrum.org/) is an open-source scholarly publishing platform created University of Michigan Library and Press working with partners from Indiana, Minnesota, Northwestern, and Penn State universities, with initial funding from the Mellon Foundation. The platform was designed primarily for authors to add or integrate digital media into their works, and for readers to view finished books online. It also appears that print book production is handled separately. Since installing Fulcrum on a server requires developer skills, most authors will submit text and media to be uploaded to a server hosted by a publisher or other organization. For example, see Fulcrum-produced books on the University of Michigan Press server at <https://www.fulcrum.org/michigan>, and note that only a portion of these are open-access books. Current documentation does not clearly explain formats authors can submit for Fulcrum to ingest.


#### Install R, RStudio, Bookdown, and a Latex Engine {-}
Below are steps we followed to setup the publishing platform for this book, using our Macintosh OS 10.14 computers. The same general principles also should apply to Windows computers. No special knowledge is required, but this may not be recommended for novice computer users. Installation steps---and inevitable problems that pop up---will be easier if users are willing to feel adventurous with their computers, or already have some familiarity with text editors, GitHub, or R Studio.

- Install R Project statistical programming language <https://www.r-project.org>, which Bookdown requires. [See screenshot](images/bookdown/1-r-download.png)
- Install the free RStudio Desktop to make R easier to use with a visual editor. [See screenshot](images/bookdown/2-download-rstudio.png)
- Inside RStudio, select the Packages tab, and select Install. [See screenshot](images/bookdown/3-packages-install.png)
- Inside RStudio, install the "bookdown" package to build your book, and select Install Dependencies. [See screenshot](images/bookdown/4-install-bookdown.png)
- Bookdown now should be successfully installed in RStudio. [See screenshot](images/bookdown/5-installed.png)
- For Bookdown to create a PDF edition of your book, you need to install a 
- Inside RStudio, install the "tinytex" package for Bookdown to create a PDF edition of your book (and see more about PDF edition below) [See screenshot](images/bookdown/6-install-tinytex.png)
- Don't forget: in RStudio console, type `tinytex::install_tinytex()` and press return to finish the installation. [See screenshot](images/bookdown/7-finish-install-tinytex.png)

#### Sidenote: If tinytex installation error {-}
- In the section above, we received this error message on our Mac computers: `/usr/local/bin not writeable`. We resolved by reading the software developer's GitHub issue <https://github.com/yihui/tinytex/issues/24> and following these steps:
- In the Mac Applications > Utilities folder, open the Terminal application.
- Carefully type `sudo chown -R `whoami`:admin /usr/local/bin` and press return.
- Carefully type (without "sudo") `~/Library/TinyTeX/bin/x86_64-darwin/tlmgr path add` and press return.
- Close the Terminal application.
- In the RStudio console, type `tinytex::install_tinytex(force = TRUE)` and press return.

#### Sidenote: Tinytex vs Xelatex {-}
- this book currently uses xelatex intstead of tinytex, to avoid some error messages. Modify this in your index.Rmd settings:
  - latex_engine: xelatex


#### Download and Build a Sample Book {-}
- Create a free GitHub account <https://github.com> to share code repositories and publish book editions online.
- In your web browser, log into your GitHub account, go to the software developer's bookdown-minimal repo <https://github.com/yihui/bookdown-minimal>, and fork a copy to your GitHub account. To learn about forking in GitHub, see this chapter <http://datavizforall.org/github.html> in the *Data Visualization for All* book.
- Install GitHub Desktop <https://desktop.github.com> to transfer files between your online GitHub repo and local computer
- In your web browser, go to your forked copy of `bookdown-minimal` and click the green `Clone or Download` button and select `Open in Desktop`. This should automatically open the GitHub Desktop application, and you can navigate to copy the code repo to a folder on your local computer.
- In RStudio in the upper-right corner, select Project > Open Project to open the `bookdown-minimal` folder on your local computer. [See screenshot](images/bookdown/8-project-open.png)
- In RStudio, open the `index.Rmd` file and make some simple edits to the text of this minimal book. For example, remove the hashtag `#` comment symbol in line 8 to "uncomment" and activate the PDF book option. Save your edits. [See screenshot](images/bookdown/9-edit-book.png)
- Optional: Use your preferred text editor, such as Atom editor <https://atom.io>, to modify the text.
- In RStudio, upper-right corner, select the Build tab, select Build Book, and choose All Formats to build both the gitbook-style static web edition and PDF edition.
- If RStudio successfully builds both editions of your minimal book, the output will be saved into your `bookdown-minimal` folder, in a subfolder named `_book`, because that's how this sample is configured. The RStudio internal browser should automatically open your web edition (and it's not a very good browser, so feel free to close it). Also, open the subfolder and inspect the PDF edition. If RStudio found any errors, they will appear in the Build viewer. [See screenshot](images/bookdown/11-successful-build.png)
- Hint: In future sessions with RStudio, you may need to select Packages tab and click Update to keep bookdown and other software packages up to date. [See screenshot](images/bookdown/12-packages-update.png)
- Close RStudio.

#### Publish your Book with GitHub Pages {-}
- Open GitHub Desktop and navigate to the `bookdown-minimal` folder on your local computer. Write a summary to commit (save) the changes you made above to your master branch, and push this version to your online GitHub repo.
- In your web browser, go to your online GitHub repo, with a web address similar to `https://github.com/USERNAME/bookdown-minimal` (insert your GitHub username).
- In your GitHub repo, select Settings, scroll down to the GitHub Pages section (which is a free web hosting service to publish your code and book editions on the public web). Select Master Branch as your source, and Save.
- Scroll down to this section again, and the web address of your published site should appear. Copy this address.
- In a new browser tab, paste the web address from above, and at the end add `_book/index.html` because this sample is configured to store the web edition of your book in this subfolder. Your web address should be similar to: `https://USERNAME.github.io/bookdown-minimal/_book/index.html`

#### Customize your Bookdown and GitHub settings {-}
- To see customized settings for this book, go to its online repository <https://github.com/ontheline/ontheline-bookdown>
- In the `_bookdown.yml` file, the output directory is set to build all book formats into the `docs` folder.
- The GitHub Pages settings for this repo (which you cannot view) is set to publish from the `master/docs` folder, to match the output directory above. This simplifies the published web address to this format: `https://USERNAME.github.com/REPONAME`
- Most of the Bookdown configuration settings appear in the `index.Rmd` file. Read more about these options in the software developer's technical guide, <https://bookdown.org/yihui/bookdown/>.
- In addition, this GitHub Pages repo is published with a custom domain name <https://OnTheLine.trincoll.edu>. Learn more about custom domain names at <https://help.github.com/articles/using-a-custom-domain-with-github-pages/>, which usually requires purchasing a domain name from a web hosting service (such as <http://ReclaimHosting.com>). Adding a GitHub Pages custom domain name creates an additional `CNAME` file in the `docs` subfolder. Be careful not to delete it (or place a copy in a subfolder for safekeeping).
- This book also includes a custom `404.html` file that was manually transferred into the `docs` subfolder, since it is not automatically built by Bookdown.
- This book also includes a custom `google-analytics-otl.html` file in the root-level of repo (where bookdown looks for it) and also is manually transferred to the `docs` subfolder (since bookdown does *not appear* to copy it to there on each build). This tracks web traffic with Google Analytics.

#### About PDF edition
The Bookdown-generated PDF edition is still a work-in-progress. Read more about various options at <https://bookdown.org/yihui/rmarkdown/pdf-document.html>. Currently using xelatex engine (see bookdown.yml settings) to avoid unicode errors, but images are not ideal.
