## Bridging the History Gap {-}

*On The Line* is written for students and residents of the Hartford region, as well as for scholars of metropolitan history. On the local level, this work of public history weaves together two vitally important stories: the rise of increasingly rigid schooling and housing boundaries that shaped metropolitan Hartford over the past century, and the civil rights struggles of families and activists to cross over, redraw, or erase these powerful lines. To learn how the city of Hartford and its surrounding suburbs became one of the most racially and economically divided regions in the northeastern United States, the book traces how government, business, and white upper-class families drew boundary lines to distance themselves from others who they perceived as a threat to their position. Moreover, to make us wiser about future prospects for change, it explores how civil rights coalitions crafted different strategies over the decades to challenge and reshape boundary lines, with mixed success, in both the education and housing sectors. More people need to learn these stories about the partitioning of the Hartford region into different towns, school districts, attendance areas, and housing zones, which created disparate social worlds with dramatic differently odds for life outcomes. Whether people grew up or went to school on one side or the other, these divisive boundaries are part of our shared history. Living and learning on the lines have profoundly shaped all of us.

For scholars, *On The Line* argues that we cannot understand the broader narrative of twentieth-century US history without the explanatory power of housing and schooling. Indeed, suburbanization was caused by multiple factors: job migration, interstate highways, tax policies, urban rebellions, and white flight. But this book argues that the dynamic relationship between housing and schooling played a central role in shaping places like Connecticut, which we have not fully understood because a prior generation of historians split these topics into separate bodies of literature, and essentially drew boundaries around these disciplinary subfields. On one side of this scholarly divide, urban and suburban historians (such as Arnold Hirsch, *Making the Second Ghetto*, and Ken Jackson, *Crabgrass Frontier*) described how housing policies and racial discrimination fueled the post-World War II decline of cities and expansion of outlying suburbs, but schools did not play a meaningful role in their equation. On one side, educational historians who followed the lead of David Tyack (*The One Best System*) focused on the rise and fall of big-city school districts, yet paid little attention to their relationship with suburbs. Whereas most educational historians halted at the city line, urban and suburban historians generally stopped at the schoolhouse door.^[@hirschMakingSecondGhetto1983; @jacksonCrabgrassFrontierSuburbanization1985; @tyackOneBestSystem1974. For an extended version of this historiographical argument, see @doughertyBridgingGapUrban2007.]
