## Outline of the Book {-}

*On The Line* seeks to bridge this disciplinary divide by showing how the dynamic relationship between schooling and housing reshaped our cities and suburbs. During the immediate post-war years of mass suburban housing, public schools in many of these formerly rural towns were seen as inferior to the big-city districts, and a deterrent to outward migration. But in the late 1950s and '60s, a convergence of three groups-real estate industry, pro-suburban government, and white middle-class homebuyers-invested in suburban public schools, marketed them to private homes, and defended their attendance boundary lines. This schooling-housing convergence became more powerful in US families' lives in the human capital market of the 1960s to today, when education credentials have become the most reliable means to transfer middle-class privilege to one's children. Americans seeking upward mobility began to embrace what we recognize today as a familiar formula: buy a home in the right neighborhood, in order to send your children to a good school, to increase their odds of being accepted into a top-ranked college, to help them to land the perfect job. Moreover, wealth-based schooling and housing boundaries became a more legitimate way for upper-class white families to defend and pass on their privileges, without resorting to overtly racial boundaries of the past, while still distancing their children from other students perceived to be less desirable peers. America's story of urban decline and suburban ascent, and civil rights struggles to challenge these inequalities, cannot be told without the interaction between two key ingredients-housing and schooling-and the boundary lines that bind them together.

This book concentrates on the metropolitan Hartford story, and is divided into multiple chapters of narrative and evidence, organized thematically and chronologically to advance key elements of the broader historical argument.

[Chapter 2: Defining City and Suburban Lines](#defining) begins by challenging us to reconsider the familiar poor cities and rich suburbs narrative that is so ingrained in our present-day thinking. But a century ago, these roles were reversed. Connecticut's capital city was the center of financial wealth, adorned by its crown jewel of public education, Hartford Public High School. Urban schools earned such a strong reputation through the early 1900s that they attracted families from outlying towns to send their children into the city's borders. By contrast, public schools in areas that we consider today to be elite suburbs, were relatively weak rural districts at this time. This part of the book begins to explain the reversal of fortunes between Hartford's city and its suburbs over time. Larger colonial-era tracts of land were carved up into smaller town boundaries, state laws formed more rigid school district lines, and suburban voters blocked urban annexation. Today's Connecticut is highly fragmented into 169 municipal governments, and most manage their own public school districts and land-use decisions, with weak regional governance. Even the phrase "metropolitan Hartford," which appears in this book, has no official nor consistent definition. As a result, self-interested suburban policies with state governmental support have generated some of the nation's highest levels of inequality between the central city and its suburbs, and also across suburbs of different socioeconomic standings.

[Chapter 3: Separating with Color and Class Lines](#separating) explains how the boundaries of white middle-class privilege have shifted over time, from explicit racial barriers to more sophisticated hurdles, and from the schooling to the housing sector. The Connecticut legislature banned schooling for out-of-state black students during the 1830s, and Hartford leaders voted to officially segregate public schools for a brief period in 1868, and proposed it again in 1917. After civil rights activists overturned these policies, Hartford officials quietly continued to separate many black and white students into the 1970s, through its decisions on locating new schools and redrawing attendance lines. In the housing sector, the color line gained more governmental support in the 1930s and '40s, with federal and local policies that openly prohibited home mortgages and public housing for blacks, and legally protected white-only property deeds. After activists overturned these governmental restrictions, the Connecticut real estate industry continued the color line through discriminatory steering and lending, even after the federal Fair Housing Act of 1968 outlawed these practices. Eventually, as overt racism became harder to defend, Connecticut's white suburbs relied more on exclusionary zoning policies, with "color-blind" rules that required higher-price single-family home construction, effectively blocking lower-wealth families, and by extension, most people of color. As a result, Connecticut's city-suburban barriers trace their legacy to color lines that have faded over time, but remain in force today primarily due to class lines, supported by local and state government.

[Chapter 4: Selling and Shopping the Lines](#selling) explores the pivotal relationship between public schooling and private housing, which fundamentally reshaped metropolitan life and upward mobility strategies in Connecticut in the latter half of the twentieth century. By contrast, in the early 1900s, when a smaller proportion of youth pursued secondary education and beyond, most families did not choose their homes based on the boundary lines of desirable public schools. Prior to the 1950s, schools were relatively weak in attracting middle-class families to the suburbs, but in post-war human capital markets, education became a powerful magnet. Pro-suburban government, real estate interests and prospective homebuyers converged to create the practice commonly known today as "shopping for schools." Agents began to advertise private homes by their location in higher status public school areas. Local school leaders competed for upper-class families by offering curricular extras. State legislators invested in suburban schools, and legitimized school-by-school rankings by publishing standardized test results. Upwardly mobile families with children sought more desirable school attendance areas, and paid higher prices for private homes that included access to this public good. Overall, the rise of shopping for schools unites the twin narratives of credentialism and consumerism in American metropolitan history.

[Part 5: Challenging the Power Lines](#challenging) tells the stories of everyday families and civil rights activists who sought to cross over, redraw, or erase schooling and housing boundaries in metropolitan Hartford, focusing primarily on the past five decades. When comparing these stories, we learn that the tools of privilege do not stand still, but evolve when confronted by civil rights challenges. In turn, this requires newer generations of activists to continually rethink and revise strategies to address the limited successes of prior years. After Connecticut civil rights advocates won legislative bans against overt racial discrimination in public housing in the late 1940s, and most private housing in the 1960s, they needed to create more sophisticated strategies to combat racial steering and redlining practices, since these were more difficult to prove without direct testing and quantitative studies. Similarly, although activists won a 1965 state constitutional amendment for equal public schools, initial efforts to implement this law were equally challenged in moving students or dollars across city-suburban district lines. This portion concludes with the 1996 courtroom victory of the *Sheff v O'Neill* school integration plaintiffs, where Connecticut's highest court outlawed the segregation of Hartford minority students, but left the specifics of the remedy to be determined by a suburban-dominated political process.

[Chapter 6: Choosing to Cross the Lines](#choosing) describes the present-day political compromises that have emerged from battles over schooling and housing boundaries. When civil rights activists finally pressured Connecticut leaders to deliver on the promise of integration with the Sheff remedies, beginning in 2003, the agreement hinged on voluntary public school choice that did not require participation by any individual, or initially, any suburban district. Instead, state leaders agreed to expand interdistrict magnet schools, with highly-desirable curricular offerings in the arts, sciences, and other specialties to attract white suburban families to voluntarily enroll their children in the same school as urban students of color. The Sheff remedy signals a tangible civil rights victory. As of 2015, state funding for 48 interdistrict magnet schools and the Open Choice city-suburban transfer program enrolls about 12,000 Hartford minority students (or 45 percent of the total) in racially integrated settings. But compromises come at a cost. Interdistrict schools merely blur the boundary lines, rather than erase the root causes of inequality. Furthermore, this voluntary integration plan protects suburban white privilege, and our data analysis shows how it favors more privileged Hartford families. The Sheff remedy has attracted critics from all sides, but the suburban-dominated state government has resisted change and threatened to unilaterally drop all support, despite the judge's order. At present, the Sheff schooling compromise-and related housing voucher policies that promise greater choice-are caught in a standoff, with suburban interests holding the upper hand.

[Conclusion: Where Do We Draw the Line?](#conclusion) offers historical reflections on present-day policy decisions *to come*.

The end of the book contains two additional chapters for readers interested in the behind-the-scenes process that resulted in this this book. [Creating On The Line](#creating) details the behind-the-scenes decisions, research methods, and web technologies used to build this open-access digital book. Also, [Teaching with On The Line](#teaching) describes how the book emerged while working with liberal arts undergraduates and community partners in metropolitan Hartford, and offers lesson ideas to help students of all ages delve into key questions and digital sources in this volume.
