# Segregating Along Color Lines {#segregating}

This chapter explains how the boundaries of white middle-class privilege have shifted over time, from explicit racial barriers to more sophisticated hurdles, and from the schooling to the housing sector. The Connecticut legislature banned schooling for out-of-state black students during the 1830s, and Hartford leaders voted to officially segregate public schools for a brief period in 1868, and proposed it again in 1917. After civil rights activists overturned these policies, Hartford officials quietly continued to separate many black and white students into the 1970s, through its decisions on locating new schools and redrawing attendance lines. In the housing sector, the color line gained more governmental support in the 1930s and '40s, with federal and local policies that openly prohibited home mortgages and public housing for blacks, and legally protected white-only property deeds. After activists overturned these governmental restrictions, the Connecticut real estate industry continued the color line through discriminatory steering and lending, even after the federal Fair Housing Act of 1968 outlawed these practices. Eventually, as overt racism became harder to defend, Connecticut's white suburbs relied more on exclusionary zoning policies, with "color-blind" rules that required higher-price single-family home construction, effectively blocking lower-wealth families, and by extension, most people of color. As a result, Connecticut's city-suburban barriers trace their legacy to color lines that have faded over time, but remain in force today primarily due to class lines, supported by local and state government.
