## The Richest City in the Nation

Over a century ago, the press declared Hartford as "the richest city in the United States" per capita, a label from the past that seems strange to anyone familiar with its extreme poverty in the present day. That tagline came from journalist Charles Clark, who wrote a cover story on Connecticut's capital city in 1876 for *Scribner's Monthly*, one of the most popular illustrated literary magazines of its time. While Clark may not have invented this slogan, he certainly popularized it, based on some loose arithmetic of the city's accumulated wealth, relative to the size of its population, approximately 40,000 people. His essay opened by surveying the value of vast financial and industrial corporations based in the downtown area. The city's well-known insurance companies, including The Hartford and Aetna, held more than $113 million in assets, which rebuilt Chicago after its disastrous 1871 fire. Added together, the city's numerous banks amassed over $50 million in deposits and capital. Five railroad lines fed Hartford's extensive factories, including Colt's Arms Manufacturing Company, "perhaps the most famous in the country" for its rifles and revolvers during the Civil War. Summed together, these businesses pushed the city's taxable property value to more than $200 million.

<iframe src="https://jackdougherty.github.io/otl-google-books-api/scribners-monthly-1876.html" width="100%" height=615></iframe>

In addition its financial assets, Clark also praised Hartford's abundant cultural riches. The nation's best-known authors, Samuel Clemens (more commonly known as Mark Twain) and Harriet Beecher Stowe (whose best-seller, *Uncle Tom's Cabin*, influenced the Civil War), both took up residence in the city, alongside many of their literary companions, editors, and publishers. In addition to serving as the state capital, Hartford prized its extensive libraries, museum, and hospital. "The Hartford school buildings are said to the finest in the State," Clark added, and called special attention to his alma mater, Hartford Public High School, the second oldest in the nation, which also enjoyed "a reputation with all the leading colleges as one of the best of all the preparatory schools.”[@clarkCharterOakCity1876] In fact, the education that young people received in the city's public school system far surpassed what was available in the outlying rural towns, known today as the suburbs.

Today we recognize Clark's "richest city" slogan as boosterism. The twenty-eight-year-old son of a local congressman was a rising reporter at the *Hartford Courant*, the nation's oldest continuously published newspaper, and would later become its editor and owner. Clark "had an investment in the city," observes historian Steven Courtney, and later served on the boards of corporations and philanthropies his essay praised.[@courtneyCommentaryWasHartford2014; on Clark, see @osbornCharlesHopkinsClark1906; @nunesLastingLegacyCharles2014; @nunesChapterFourFighting2014] He did not offer a definitive statement on Hartford's total wealth per capita, nor any direct comparison to financial statistics for other cities, to the extent they were available. Today, the idea of measuring a city by the wealth of its total corporate wealth, rather than the assets actually owned by individual residents, makes little sense. In 1903, nearly four decades after Clark's essay, skeptics questioned some of its claims. One critic was Alexander Merriam, a Hartford Theological Seminary professor in the brand-new field of sociology. Although Hartford was still "computed as one of the richest cities of its size in the country," he observed, "local wealth is not so large and available as the statistical aggregate might seem to indicate." Residents included both "wealthier citizens. . . scattered in different parts of the city" and also "a slum of almost the first magnitude" of the poorest citizens along the banks of the Connecticut River. While Hartford still had significant pockets of wealth, they were not uniformly distributed. In fact, while Samuel Clemens lived in Hartford, he and his co-author satirically named this era the Gilded Age, referring to a thin gold layer that symbolizes wealth, but masks underlying social problems.[@merriamSocialSignificanceSmaller1903; reprinted as @merriamSocialConditionsSmaller1903; see also skepticism about the corporate assets underlying the "richest city" claim in @RichestCity1903; @twainGildedAgeTale1873]
