# Excluding Through Zoning Lines {#excluding}
This chapter makes visible the hidden history of zoning, the key to understanding where people live in suburban Hartford and other economically and racially segregated metropolitan regions. In general, **zoning** refers to rules governing how land can be used. Some zoning policies have progressive goals, such as separating industrial factories from residential neighborhoods, in order to protect the public health and welfare of the larger community. But in present-day debates, **exclusionary zoning** means policies that favor expensive single-family home construction by requiring large amounts of land per family, rather than more affordable multi-family homes with less land per family. In this way, exclusionary zoning gave local governments a legally defensible way to limit who can afford to move into their community.

In Connecticut, the origins of exclusionary zoning can be traced back to efforts by the West Hartford town government to block a Hartford Jewish grocer from building a store in a residential neighborhood in the early 1920s. Although suburban leaders failed to block this particular store, they helped spark a statewide political movement to create local zoning laws to control what type of real estate could be developed in the future. West Hartford town leaders raced to become Connecticut's first municipality in 1924 to enact local zoning ordinances that a new state law enabled. They hired national experts who designed minimum-land rules to ensure that only single-family homes for middle- and upper-class families would be built in new suburban neighborhoods, and to deter two- and three-family homes and apartments that might attract lower-income families they deemed as undesirable.

Unlike overtly racist housing barriers described in prior chapters of this book---such as [mortgage redlining](lending.html), [racial covenants](restricting.html), and [segregated public housing](public-housing.html)---exclusionary zoning laws do *not* directly refer to race, religion, or nationality. Instead, exclusionary zoning pretends to be color blind and claims to benefit the public good of the community it protects, while ignoring the rights of people who cannot afford to purchase their way inside. Although civil rights activists successfully pushed for the 1968 Fair Housing Act and other laws that prohibited race-based housing discrimination, exclusionary zoning cleverly avoided this obstacle and continues to exist in Connecticut and many other states today, largely in the same way it was designed a century ago. To understand present-day debates over zoning, and to envision a path forward, we need to look backwards to learn how we arrived here.

*An abbreviated version of this chapter was published in Connecticut Explored magazine in 2023.*^[@doughertyRiseExclusionaryZoning2023]
