## Restricting with Property Covenants {-}
*by [Tracey Wilson, Vianna Iorio, and Jack Dougherty](#contributors)*

> No persons of any race except the white race shall use or occupy any building on any lot except that this covenant shall not prevent occupancy by domestic servants of a different race employed by an owner or tenant.  
> -- High Ledge Homes, West Hartford, Connecticut, 1940.[@highledgehomesinc.AgreementConcerningBuilding1940]   

To many readers, the shockingly blatant racism of the above sentence seems as though it could have been pulled from some long-ago segregation policy of the Deep South. Instead, it came from the Deep North, and represents a forgotten chapter of White suburban history. This race restrictive covenant appears in a government-sanctioned property deed from 1940, inserted by a real estate property developer for High Ledge Homes, a tract of about 70 single-family houses located along South Main Street in West Hartford, Connecticut. Across the nation from the 1920’s to 1948, individual property owners, homeowners’ associations, and real estate developers employed racially restrictive covenants to prohibit anyone not considered to be part of the “white race” from sale or residency. The only non-white exceptions allowed by most racial covenants were for domestic servants. Furthermore, racially restrictive covenants were backed by the court system up until 1948. If a Black renter or homebuyer attempted to move into a house with a restrictive covenant, any White resident in that suburban development could sue to remove them from the neighborhood. While it may be difficult for present-day residents to imagine this kind of explicit racism in the heart of New England, this chapter uncovers the missing history of state-supported discrimination in multiple housing developments in suburban West Hartford, and most likely many other towns across Connecticut.

##### Explore the Map: Restrictive Covenants in Hartford area, 1940s {-}
*Click on colored rectangles in this [full-screen interactive map](https://ontheline.github.io/otl-covenants/index-frame.html) to view restrictions that landowners wrote into property deeds in the 1940s, typically to prohibit occupants “other than the Caucasian race." The U.S. Supreme Court approved these restrictions in the 1926 Corrigan v. Buckley case, but later declared them unenforceable in the 1948 Shelley v. Kraemer decision. Yet these restrictions still exist in official property records. To date, we have found 5 race restrictive covenants in West Hartford. If you know of similar restrictions, by race or religion, anywhere in Connecticut, [contact the author](#contact-the-author). View [map historical sources and the code](https://github.com/OnTheLine/otl-covenants), developed by Ilya Ilyankou and Jack Dougherty, based on an earlier map created with UConn MAGIC.^[@ilyankouMapRestrictiveCovenants2017; universityofconnecticutlibrariesmapandgeographicinformationcenterRaceRestrictiveCovenants2012]*

On the whole, race restrictive covenants were more pervasive in other Northern and Western cities, such as Chicago and Los Angeles, than the metropolitan Hartford region. Based on our search of property records to date in West Hartford, the largest suburb of Hartford, we found only 5 race restrictive covenants, all created during the early 1940s. These covered about 200 parcels of land, or around 3 percent of the 6,000 single-family homes that had been constructed in the town around that time. Learn more in this book about [How We Found Restrictive Covenants](creating.html#how-we-found-restrictive-covenants). In this suburb, race restrictive covenants did not appear in all neighborhoods that were developed during this time period, and where they did exist, they did not necessarily apply to every house in that neighborhood. Instead, West Hartford relied more on racial barriers in public housing, by real estate agents, and exclusionary zoning ordinances to restrict non-White and low-income residents. Eventually, race restrictive covenants faded away after the US Supreme Court ruled in 1948 that governments could not enforce these individual agreements.

But their legacy continues to shock and influence us decades later. On a tangible level, homeowners who purchased covenant-protected property gained White privilege and passed along its financial benefits to their future generations. On a historical level, the shocking story of racial covenants in the Deep North serve as an important reminder of the state-sanctioned White supremacy that came to shape Connecticut suburbs.

The story of restrictive covenants begins with the U.S Supreme Court case *Corrigan v. Buckley* in 1921. White property owners in the Dupont Circle neighborhood of Washington D.C. formed a property owners’ association which utilized racially restrictive covenants to keep out Black homebuyers. The dispute arose when White owner John Corrigan attempted to sell his house to an African-American buyer, Irene Curtis, which violated the property’s racial covenant. Learning of this violation, White neighbor Irene Buckley brought suit to enforce the race restrictive covenant and stop the property sale.

As the case worked its way through the nation’s legal system, the courts upheld the racial covenant. First, the District of Columbia Supreme Court approved the racial prohibition and cited existing legal segregation in schools and public recreational facilities as precedent. Next, upon appeal, the District of Columbia Court of Appeals also ruled in favor of the covenant and cited that African Americans were free to include the same kind of racially exclusive language against Whites in their own property deeds. When the U.S. Supreme Court made their ruling in 1926 the justices unanimously affirmed the lower court decisions by refusing to hear the case on the grounds that they lacked jurisdiction. When Justice Edward Sanford delivered the Court’s opinion, he narrowly defined the Constitution’s guarantee that no person should “be deprived of life, liberty, or property, without due process of law” as it applied to *Corrigan v. Buckley*. Sanford asserted that while the Fifth Amendment limited the actions of the federal government, it did not apply to individuals entering a private contact, such as a restrictive covenant. Moreover, he argued that the Thirteenth Amendment did not protect individual rights of blacks, and the Fourteenth Amendment again referred to actions of the state, not of private individuals. Therefore, the 1926 *Corrigan v. Buckley* decision reaffirmed the right of property owners to legally enforce race restrictive covenants, while ignoring that the court system itself acted as governmental support for segregation. Their interpretation of the Constitution would prevail for over twenty years.^[@CorriganBuckley1926; @prologuedcMappingSegregationWashington2015]

In emerging suburban communities like West Hartford, Connecticut during this period, property owners inserted different types of deed restrictions to increase their desirability. Beginning in the 1910s, individual homeowners began to add value restrictions, which required that future homes constructed on the land must be above a minimum dollar amount. Real estate developers also began to insert home-value restrictions to cover entire subdivisions. Some also added other types of value restrictions, such as requiring homes to be built above a minimum square footage or sold above a minimum dollar amount, which also raised the overall cost. While these value restrictions effectively limited neighborhoods to wealthier White families, they did not yet contain explicitly racial prohibitions.

Race restrictive covenants came to West Hartford in the early 1940s. During the Depression, rural farmland became more valuable as prospective housing, if the developer could attract city dwellers to the emerging suburbs. Local builder Rupert G. Bent purchased the 47-acre Wooley estate on South Main Street, across from the Rockledge Golf Course, for $30,000 in 1937, and subdivided the land into 100 building lots. Over the next two years, Bent heavily publicized and sold 34 homes during these tough economic times, including several to incoming executives at Hartford’s major insurance companies. But Bent eventually sold the remaining land to another developer, Edward Hammel, president of High Ledge Homes, Inc. Described as a “builder of fine homes” in wealthy areas of Westchester County, New York, and Fairfield County, Connecticut, Hammel introduced new methods to make unsold property more marketable. His “uniform plan of development” added several restrictions to property deed that prohibited multi-family homes, small building plots, and occupants “of any race except the white race.” This restrictive covenant guaranteed that homebuyers would belong to an exclusively White, upper-class neighborhood, and represented a growing trend among real estate interests across the nation since the 1920s. Hammel’s racial covenant appears to have been the first of its kind in West Hartford, and then at least four other developers added the same restriction over the next year.^[@100NewHomes1940. See race restrictive covenants in West Hartford property deeds in @ilyankouMapRestrictiveCovenants2017.]

Advertising for High Ledge Homes did not mention its racial barrier, but emphasized its exclusivity. A 1940 ad listed the development for “anyone interested in a low or medium home price of the better class,” located in the “A” region of town’s zoning ordinance, which required single-family building lots to be at least 9,000 square feet, and kept out lower-class families. “You’ll like your neighbors” in this growing community, the pitch continued. It also mentioned “West Hartford’s famous schools,” one of the earliest real estate advertising references to this young suburb’s public education system, and perhaps a premature one, given the better reputation of Hartford’s city schools into the 1950s.[@AdModernHomes1940]

![Although High Ledge Homes did not openly publicize their Whites-only property covenant, their advertising promised homebuyers that "you'll like your neighbors." Source: Hartford Courant, 1940, reprinted under fair-use copyright guidelines.[@AdModernHomes1940]](images/1940-03-31HC-HighLedgeHomesAd.jpg)

While the High Ledge Homes race restrictive covenant stated that any violator could be brought to court by another property owner within the development, winning this lawsuit would be more difficult in practice. The reason was two different types of restrictive covenants. A deed covenant, like the one in High Ledge Homes, was legally considered to be a contract between the original property owner and the buyer. This made it more difficult for a neighbor, who technically was not part of the contract between owner and buyer, to establish a stake in its violation. By contrast, a petition covenant, like the one described in the *Corrigan v. Buckley* case in Washington DC, was easier to enforce in court, because neighborhood associations gathered the signatures of all homeowners, meaning that all were legal parties to this group contract.^[@rothsteinColorLawForgotten2017, p. 79; @prologuedcMappingSegregationWashington2015] Even though race restrictive covenants appeared in West Hartford in 1940, they had a longer legacy and more powerful influence in other cities.

Race restrictive covenants were more pervasive in many Northern and Western cities beyond the metropolitan Hartford region. In Chicago and Los Angeles, estimates of properties covered by racial covenants in the 1940s ranged from 50 to 80 percent. In Seattle, developers attached restrictive covenants to tens of thousands of homes in the city and its surrounding suburbs, which created a ring outside the central city of White-only neighborhoods. As a result, large numbers of African American, Asian, and Jewish residents were forced into the only housing available to them, and became highly concentrated into the Central Area and International Districts of the city. In Detroit, researcher Richard Rothstein estimates that white homeowners, real estate agents, and developers organized 192 associations to promote racial exclusion” from 1943 to 1965. And in St. Louis, where the landmark *Shelley v. Kraemer* case eventually made racial covenants unenforceable, the widespread prevalence of white-only covenants meant that only 2.5 percent of new housing construction was devoted to Black homeseekers in 1948.^[On the 50 percent estimate in Chicago, see @coatesCaseReparations2014. For higher estimates in Chicago and Los Angeles, see @unitedstatescommissiononcivilrightsUnderstandingFairHousing1973, p. 3; @gregorySegregatedSeattle2010; @rothsteinColorLawForgotten2017, p. 80; @gondaUnjustDeedsRestrictive2015, p. 31.]

While most restrictive covenants were racial, some also prohibited property ownership based on religion, specifically against Jews. Simon Bernstein, an attorney and Democratic member of the Hartford City Council, pressed the Judiciary Committee in Connecticut’s General Assembly to outlaw restrictive covenants “pertaining to nationality, color and religious belief” in 1947. He described his interest in a local case where the property deed limited the sale to “non Semitic persons of the Caucasian race.” Bernstein called for a bill to invalidate all restrictive covenants on the grounds that this “un-American practice... is contrary to public policy.” Without governmental action, Bernstein declared that “our town clerks are unwitting tools in transcribing prejudices on record, and are thus proclaiming by such governmental publication not only the evil deed, but also immunity against the world for such prejudices.” But Connecticut legislators waited for action from the federal government.^[@BernsteinSeeksEnd1947; @StateLawSought1947. In our oral history interview with Simon Bernstein at age 98, he recalled details about a race restrictive case in West Hartford which was settled out of court, but not the religion and race case briefly mentioned in this 1947 press account. See @bernsteinOralHistoryInterview2011. Tracey Wilson described anecdotal accounts of anti-Jewish and anti-Catholic covenants in West Hartford, but we have not yet found documentary evidence. See @wilsonHighLedgeHomes2018.]

By the late 1940’s across the nation, civil rights activists successfully began to turn the tide against racial covenants, both in the courts and the realm of public opinion. The US Supreme Court heard *Shelley v. Kraemer*, a compilation of race restrictive covenant cases that NAACP attorneys advanced from St. Louis, Detroit, and Washington, DC. President Truman’s Committee on Civil Rights came out against racial covenants, and the U.S. Department of Justice filed a brief also condemning this discriminatory policy. In its 1948 ruling, the Supreme Court agreed that private parties could voluntarily agree to race restrictive covenants, but for the judicial system to enforce these agreements qualified as a discriminatory state action, and therefore violated the Equal Protection clause of the Fourteenth Amendment. Therefore, the *Shelley v. Kraemer* ruling overturned the logic of the 1926 *Buckley v. Corrigan decision*, which refused to acknowledge legal enforcement of contracts as an act of government. But race restrictive covenants did not disappear overnight. The Federal Housing Administration (FHA) continued to require racial covenants for properties it insured until 1950, and continued to back mortgages for some white-only properties until 1962. Also, several state courts resisted the *Shelley* decision until a subsequent US Supreme Court decision in 1953. Finally, some local governments continued to accept unenforceable race covenants as legal property documents until this practice was overruled by the federal courts in 1972.[@ShelleyKraemer1948; @rothsteinColorLawForgotten2017 pp. 85-91; @MayersRidley1972.]

Although race-restrictive covenants were no longer legally enforceable after 1948, their legacy continued to influence later generations. Whites who bought into restricted West Hartford neighborhoods during the 1940s benefitted financially from government-sanctioned segregation that boosted property values. Decades later, their descendants also benefitted from this inherited wealth. Even after restrictive covenants no longer had judicial backing, the fact of their existence—--and the all-White neighborhoods they created—--sent a signal to potential buyers about the racial preferences of their neighbors. Years after the Shelley decision, some West Hartford homebuyers were told by their lawyers that a non-enforceable racial covenant still existed on their property deeds. And Black homebuyers had to decide whether or not to live in a neighborhood with a documented past of being openly hostile to their presence.[@everettOralHistoryInterview2011; @brooksSavingNeighborhoodRacially2013]

Most present-day residents of West Hartford’s High Ledge Homes development were shocked to learn that their neighborhood had been protected by a 1940s White-only covenant, and sought to make sense of its meaning on their lives. Debra Walsh, an educator and actor, reflected on the White privilege that was attached to her decision to buy her home in 2010. Although she had believed that the North had not exhibited such explicit racist policies, the direct evidence of race restrictive covenants convinced her that “West Hartford made a concerted effort to stay White and WASPy and that contributes to the feel of the neighborhood.” Walsh acknowledged how the explicit racism of the covenants in her own neighborhood made her feel uncomfortable with the White privilege she experiences. “It's really hard to look really deep within and answer those questions,” she explained, “... when you live in the dominant class. Like you don't know how to answer it.” Even though she knew the covenants are no longer enforceable, Walsh could see how “the legacy of the piece of land gets passed on to a feeling of a neighborhood,” a sense of White exclusivity that pervades even today, when barriers take on less overtly racial language.

￼##### Watch the Video: Debra Walsh Oral History Interview, 2011
<iframe src="https://player.vimeo.com/video/27299734?portrait=0" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
*Watch the [oral history video or read the transcript of the interview with Debra Walsh](http://digitalrepository.trincoll.edu/cssp_ohistory/21) to hear how she learned about a race restrictive covenant in her West Hartford neighborhood.^[@walshOralHistoryInterview2011]*

Yet while racial covenants make White West Hartford residents uncomfortable about the past, they remain an important piece of history, a hidden chapter that deserves more attention. Susan Hansen, a librarian and White resident who bought her home in the High Ledge Homes neighborhood in the 1990s, reflected on this theme during a present-day oral history interview. “I think this is something that people should know,” Hansen observed, “because there are people still living on my street who were here then, who must have been fully aware.” Hansen also emphasized the importance of knowing that racial covenants were not something that happened only in the Deep South long ago, but are a very recent part of Northern suburban history that should not be whitewashed out of memory. As Hansen concluded, “We need to know that we were being idiots up here, too, and it wasn't somewhere else. It was here. It's still here.”

##### Watch the Video: Suan Hansen Oral History Interview, 2011
<iframe src="https://player.vimeo.com/video/27300618?portrait=0" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
*Watch the [oral history video or read the transcript of the interview with Susan Hansen](http://digitalrepository.trincoll.edu/cssp_ohistory/17) to hear her reflections about a race restrictive covenant in her West Hartford neighborhood.^[@hansenOralHistoryInterview2011]*

*About the contributors: Tracey Wilson (Trinity 1976) wrote the first draft of this essay for a monthly newspaper, which also appears in her book, Life in West Hartford.^[@wilsonTakingStockHigh2010; @wilsonHighLedgeHomes2018]. Vianna Iorio (Trinity 2019) and Jack Dougherty expanded this essay in collaboration with her. Ilya Ilyankou (Trinity 2018) and Jack Dougherty developed the interactive map, based on an earlier version created with UConn MAGIC.^[@ilyankouMapRestrictiveCovenants2017; universityofconnecticutlibrariesmapandgeographicinformationcenterRaceRestrictiveCovenants2012] Also, Katie Campbell Levasseur (Trinity 2011) researched restrictive property covenants, and both she and Candace Simpson (Trinity 2012) conducted oral history interviews.*
