# Selling and Shopping the Lines {#selling}

This chapter explores the pivotal relationship between public schooling and private housing, which fundamentally reshaped metropolitan life and upward mobility strategies in Connecticut in the latter half of the twentieth century. By contrast, in the early 1900s, when a smaller proportion of youth pursued secondary education and beyond, most families did not choose their homes based on the boundary lines of desirable public schools. Prior to the 1950s, schools were relatively weak in attracting middle-class families to the suburbs, but in post-war human capital markets, education became a powerful magnet. Pro-suburban government, real estate interests and prospective homebuyers converged to create the practice commonly known today as "shopping for schools." Agents began to advertise private homes by their location in higher status public school areas. Local school leaders competed for upper-class families by offering curricular extras. State legislators invested in suburban schools, and legitimized school-by-school rankings by publishing standardized test results. Upwardly mobile families with children sought more desirable school attendance areas, and paid higher prices for private homes that included access to this public good. Overall, the rise of shopping for schools unites the twin narratives of credentialism and consumerism in American metropolitan history.

MORE TO COME...  This chapter expands on themes that previously appeared in Jack Dougherty, “Shopping for Schools: How Public Education and Private Housing Shaped Suburban Connecticut,” *Journal of Urban History* 38, no. 2 (March 2012): 205–24, http://juh.sagepub.com/content/38/2.
