# Blurring the Lines with Choice Policies {#blurring}

This chapter explains that despite successful legal challenges, school and housing boundaries remain largely intact in Connecticut, though somewhat blurred by a set of compromises around public school choice and housing voucher policies that allow some, but not all, individuals to cross over these lines. After school integration activists sued Connecticut officials over unconstitutional district boundaries in the *Sheff v O'Neill* case, the state's highest court outlawed the segregation of Hartford's Black and Brown students in 1996, but left the specific remedy to be determined by a suburban-dominated political process. Connecticut's 2003 school integration settlement hinged on voluntary public school choice that did not require participation by any individual, or initially, any suburban district. Instead, state leaders agreed to expand interdistrict magnet schools, with highly-desirable curricular offerings in the arts, sciences, and other specialties to attract white suburban families to voluntarily enroll their children in the same school as urban students of color. The Sheff remedy signals a tangible civil rights victory. As of 2015, state funding for 48 interdistrict magnet schools and the Open Choice city-suburban transfer program enrolls about 12,000 Hartford minority students (or 45 percent of the total) in racially integrated settings. But compromises come at a cost. Interdistrict schools merely blur the boundary lines, rather than erase the root causes of inequality. Furthermore, this voluntary integration plan protects suburban white privilege, and our data analysis shows how it favors more privileged Hartford families. The Sheff remedy has attracted critics from all sides, but the suburban-dominated state government has resisted change and threatened to unilaterally drop all support, despite the judge's order. At present, the Sheff schooling compromise---and related housing voucher policies that promise greater choice---are caught in a standoff, with suburban interests holding the upper hand.

MORE TO COME... This chapter will expand on themes that previously appeared in:

Jack Dougherty, Jesse Wanzer, and Christina Ramsay, “Sheff v. O’Neill: Weak Desegregation Remedies and Strong Disincentives in Connecticut, 1996-2008,” in *From the Courtroom to the Classroom: The Shifting Landscape of School Desegregation*, ed. Claire Smrekar and Ellen Goldring (Cambridge, MA: Harvard Education Press, 2009), 103–27, http://digitalrepository.trincoll.edu/cssp_papers/3/.

Jack Dougherty, Jesse Wanzer, and Christina Ramsay, “Missing the Goal: A Visual Guide to Sheff v. O’Neill School Desegregation: June 2007” (Hartford, Connecticut and Storrs, Connecticut: The Cities, Suburbs and Schools research project at Trinity College and the University of Connecticut Center for Education Policy Analysis, 2007), http://digitalrepository.trincoll.edu/cssp_papers/6/.

Dana Banks and Jack Dougherty, “City-Suburban Desegregation and Forced Choices: Review Essay of ‘The Other Boston Busing Story’ by Susan Eaton,” *Teachers College Record* 105 (2004): 985–98, http://digitalrepository.trincoll.edu/facpub/21/.

Jack Dougherty et al., “School Information, Parental Decisions, and the Digital Divide: The SmartChoices Project in Hartford, Connecticut,” in *Educational Delusions? Why Choice Can Deepen Inequality and How to Make Schools Fair*, ed. Gary Orfield and Erica Frankenberg (Berkeley: University of California Press, 2013), 219–37, https://books.google.com/books?id=x9AlDQAAQBAJ&lpg=PR1&pg=PA219.
