## A Digital History Dialogue {- #digital-history-dialogue}
*by [Jack Dougherty](authors.html) with editors of The Metropole blog of the Urban History Association*

*The editors of the "Digital Summer School" series of [The Metropole](https://themetropole.blog), the official blog of the Urban History Association, invited me to dialogue with them about the process of creating On The Line, and gave me permission to republish the essay and add footnotes.*[@DigitalSummerSchool2019]

### Digital Summer School: On The Line in Metropolitan Hartford, Connecticut {-}
This is the second installment in our annual Digital Summer School series which highlights digital humanities projects focusing on urban history...

Featured Project: Jack Dougherty, On the Line: How Schooling, Housing, and Civil Rights Shaped Hartford and its Suburbs

**Why did you establish this digital project, meaning why a digital book rather than your more traditional academic text? Who do you see as its audience and why?**

Many historians have a bad habit of splitting our work into separate categories, such as “digital projects” versus “scholarly books.” Some institutional factors feed this division, such as revenue-driven publishers (who depend on book sales) and conventional tenure committees (who cannot imagine how to evaluate digital projects). But this false dichotomy between projects and books does not serve our broader interests as academic authors. In our field of history, as the average scholarly monograph sells only a few hundred copies, and the retail price tag approaches $50 per copy or higher, our audience is increasingly likely to search on the web for historical sources and interpretation, and to view these results in their browsers.  In today’s digital context, dividing projects and books is not a viable path; we need options to merge them into one.

Kristen Nawrotzki and I made this general argument in our introduction to [Writing History in the Digital Age](https://muse.jhu.edu/chapter/1030699). Over twenty-five contributors and our publisher, the University of Michigan Press, agreed to share our peer-reviewed publication under an open-access license, where readers can discover and view the full-text book on the web (for free) or in print (for a reasonable price). Scholars holding full-time jobs in academic institutions operate primarily in a reputation-based economy. If readers can access our ideas with our names attached and determine them to be of high-quality, then our value goes up. By contrast, if our ideas are locked inside hard-to-access books or behind paywalls, regardless of their quality, our reputations among readers will suffer. My thinking about these issues continued to evolve, and I experimented further with blending web technology and book production, as I co-edited a second open-access book, with Tennyson O’Donnell, [Web Writing](http://webwriting.trincoll.edu), and launched an open-access textbook with Ilya Ilyankou, [Hands-On Data Visualization](https://HandsOnDataViz.org) (in-progress).^[@nawrotzkiIntroduction2013, @doughertyWebWritingWhy2015, @doughertyHandsOnDataVisualization2021]

These three works illustrate lessons I learned while working on my current book, _[On The Line: How Schooling, Housing, and Civil Rights Shaped Hartford and its Suburbs](http://ontheline.trincoll.edu)_ (in-progress, under contract with Amherst College Press). Set in Connecticut’s capital region, the book makes visible the hidden boundaries that have divided American cities and suburbs over the past century, as well as the civil rights struggles of families and activists who crossed over, redrew, or erased these powerful lines. As a work of history, _On The Line_ blends textual narrative and digital sources into one book, with web and print editions. Perhaps it’s most appropriate to call it a digital-first book, because the richest edition is the one that appears on the open web. The narrative is wrapped around digital evidence---including interactive maps, oral history audio and video, and scanned documents---to make racial and class boundaries visible to broader audiences and to amplify the voices of people who challenged these lines.

<!-- TODO: INSERT IMAGE -->

<!-- Screenshot from 1985 video of Saundra Foster explaining why she and other Black parents were arrested by a predominantly White suburb in the [Jumping the School District Line](jumping.html) section in this book. -->

**How did this project come to fruition? What obstacles did you have to overcome?**

Thanks to the wonderful [Way Back Machine](https://archive.org/web/) by the Internet Archive, I took another look at the first version of _[On The Line that I published on the public web in 2010](https://web.archive.org/web/20100614053219/http://ontheline.trincoll.edu/)_. At that very early stage, I presented some dreams and demos to obtain grant funding and naively predicted to finish everything by 2012 (Ha!) This early version also reminded me that my previous publishing partner insisted I create two interconnected yet separate products---a digital repository (free) and a scholarly book (for sale)---each designed to stand alone, but to refer readers back and forth. Under this early model, readers would have to buy or borrow the book to read the text and go to the companion website to explore the interactive maps, videos, and other digital elements. Honestly, I’m glad that I didn’t finish on my initial deadline, under the restrictive terms of this proposed publishing arrangement, since the final product would have been disappointingly fragmented.^[https://web.archive.org/web/20100614053219/http://ontheline.trincoll.edu/]

The truth is that the origins of _On The Line_ can be traced back to my personal frustration with the status quo of scholarly communication. “Why separate the digital project and the book?” I recall asking. “Why not create a better book that unifies text and sources into one product?” I began exploring open-source digital tools that merged web and PDF publishing into one workflow. First the [Anthologize](http://anthologize.org/) WordPress beta plugin (by the One Week One Tool team at the Center for History and New Media, George Mason University), then the Pressbooks/Open Textbook/WordPress plugin platform (by [PressBooks](https://pressbooks.com/) and [BC Campus](https://opentextbc.ca/)), and now I use the [Bookdown](https://bookdown.org/) package (by RStudio). Each step has brought me closer to an improved workflow: composing easy-to-edit text that cleanly produces a web edition, with embedded interactive maps and videos, and a PDF edition, with static screenshots and links to interactive web content. Fortunately, I work with a supportive group of current and former students, librarians, and IT staff, because building an ambitious digital-first book like this one involves many steps: designing and coding interactive historical maps; transcribing and hosting oral history audio and video; managing citations and external links; future-proofing; and embedding all of this content into web and print formats. I’m not a speedy writer, and managing all of these steps has slowed me down even further.

**On a purely functional level, when considering the project’s internal structure, how did you think about incorporating aspects of _On the Line_ such as its interactive maps, videos, and other features?**

As a historian, my job is to tell meaningful true stories about the past. For this book in particular, the goal is to help readers see the “invisible” race and class boundary lines that have increasingly divided city and suburban residents over time, and to draw attention to the ways that families and activists sought to cross over or erase lines, such as movements for school integration and inclusionary zoning. Showing how these people tell their own civil rights stories in oral history video clips is more powerful than merely retelling their stories in the text. While working on each chapter, often with student co-authors, we continually ask these types of questions: _How can we tell stories that connect with our present-day readers? How can we persuade readers to explore and accept our interpretation of the evidence? And how can we guide both local and distant readers through spatial and historical change in our place-based narrative of a central city and its diverging suburbs?_ Creating this type of book requires traditional research and writing, but also dreaming up digital sources -- interactive maps, video clips, and digitized documents -- to embed into the narrative and illustrate our analysis. Some of my best teachers in this genre have been digital journalists (such as [Alvin Chang](http://alvinschang.com/), formerly at CTMirror.org, now at Vox.com).

For example, consider how historians have published over time about “redlining,” or discrimination in financial services based on people’s residence, typically linked to their race or ethnicity. Ken Jackson’s book, _Crabgrass Frontier_ (1985), introduced many readers to the 1930s Home Owners’ Loan Corporation (HOLC) and their color-coded neighborhood appraisal maps, which he quoted from and included an image of to demonstrate their segregative intent. Subsequent scholars such as [Amy Hillier](http://doi.org/10.1177/0096144203029004002) (2003) analyzed archival records with spatial computing methods and questioned whether actual HOLC lending practices matched this intent. A decade later, historians Robert K. Nelson, LaDale Winling, Richard Marciano, Nathan Connolly and their colleagues released their _[Mapping Inequality](https://dsl.richmond.edu/panorama/redlining/)_ digital history project (2016), with its impressive compilation of over 150 HOLC maps and appraisals, with commentary. In _On The Line_, former student Sean McGann and I [co-authored a chapter](https://ontheline.trincoll.edu/lending.html) that interprets this redlining history with a Hartford-area narrative. The chapter is illustrated with an interactive map of neighborhood appraisals created with the Map and Geographic Information Center (MAGIC) at University of Connecticut Libraries and the assistance of Trinity College graduate Ilya Ilyankou. The eye-catching redlining maps pull local readers further into the _On The Line_ narrative, and allow them to explore archival documents for specific neighborhoods. But our book also argues that other federal programs, such as the Underwriting Manuals of the Federal Housing Administration, which are not as visually attractive as the HOLC maps, may have been more influential in segregating suburbs. Overall, this digital-first book delivers a hybrid combination of textual interpretation and interactive sources that, in my view, is vastly superior to the alternative: a separate book and web site.

<!-- TODO: INSERT IMAGE -->

<!-- Screenshot from [Federal Lending and Redlining](lending.html) section in this book. -->

**What role do digital projects like _On the Line_ play in the field of history? Where do you see this project and others like it going in the future?**

Based on local feedback, I know that _On The Line_ has already begun to achieve one of its primary goals for Hartford-area audiences: to educate residents on ways that housing and education barriers have shaped our city and suburbs, and about the strategies used by activists and families who fought back against them. Although it’s still a book-in-progress, my student co-authors and I are publishing chapters and sources, as we complete them, on the open web. Our analytics tell us that thousands of readers have discovered this history, and dozens of local organizations and schools have invited us to give public presentations. Not bad for a not-yet-finished book.

As for the broader historical profession, another goal is for _On The Line_ to help change the way we envision scholarly communication, by offering a reproducible example of blending textual narrative and digital sources into a book with both web and print editions. But I don’t have much evidence of progress to share. Look again at the wording of the question above, which refers to _On The Line_ as a “digital project” rather than a “book.” It’s surprising to me how slowly the historical profession is creeping into the digital age, while keeping its traditional publishing paradigms intact. Relatively few historians appear to be writing digital-first books that genuinely blend textual narrative and digitized sources. I fully realize that these types of books require more work by collaborative teams, not just individual scholars; a wider range of skills not typically taught in history graduate schools; and sources of both start-up and sustainable funding. When I began work on this nearly a decade ago, I sincerely believed that more historians would be moving in this direction. Yet it still feels lonely to me. (While typing these words, I secretly hope to hear back from readers who will prove me wrong and share links to other digital-first books that blend text and evidence.)

**It seems over the past few years two aspects of urban history have arisen 1) greater emphasis placed on education as key factor in suburban development notably in the case of your work here and others such as Ansley Erickson and 2) efforts by more academic and popular historians (I’m thinking of perhaps Richard Rothstein’s *The Color of Law* which fundamentally synthesized a large body of work) to really grapple with how suburbs and their attendant segregation came to be. How do you explain these developments which in many ways are embodied by the project itself?**

Yes, I’ve been very impressed by recent works on the historical relationship between housing and education, such as Ansley Erickson’s _[Making the Unequal Metropolis](http://www.worldcat.org/oclc/1008906572)_ (2016), Richard Rothstein’s _[The Color of Law](http://www.worldcat.org/oclc/959808903)_ (2017), and others. This may be a case where historians are just now catching up with our audiences. For several decades, privileged Americans and our politicians have understood the growing two-way equation between housing and schooling: where you live shapes your children’s education, and their level of education shapes their future income and where they can afford to live. So why has it taken historians so many decades to write about this?

The “[Bridging the History Gap](https://ontheline.trincoll.edu/bridging.html)” section of _On The Line_ argues that we have not fully understood how this dynamic relationship between housing and schooling played a central role in shaping metropolitan America because a prior generation of historians split these topics into separate bodies of literature and essentially drew boundaries around these disciplinary subfields. On one side of this scholarly divide, urban and suburban historians, such as Arnold Hirsch, _Making the Second Ghetto_, and Ken Jackson, _Crabgrass Frontier_, described how housing policies and racial discrimination fueled the post-World War II decline of cities and expansion of outlying suburbs, but schools did not play a meaningful role in their equation. On one side, educational historians who followed the lead of David Tyack (_The One Best System_) focused on the rise and fall of big-city school districts, yet paid little attention to their relationship with suburbs. Whereas most educational historians halted at the city line, urban and suburban historians generally stopped at the schoolhouse door. So it’s a refreshing development to see newer historical works by Ansley Erickson, Matthew Lassiter, and others blur these boundaries.

**So far, what moment or event related to your digital project comes to mind when I say greatest achievement or unique insight?**

Years ago, when teaching or presenting about the history of cities, suburbs, and schools, I used to “talk with my hands,” waving them around in the air in my feeble attempt to visually represent racial and economic change across neighborhoods over time. Now I teach and give talks with interactive historical maps. Seems to be a much better way to communicate about urban history, and less annoying for the audience.

<!-- TODO: INSERT IMAGE of me talking with my hands -->

_Jack Dougherty is Professor of Educational Studies and Director of the Center for Hartford Engagement and Research (CHER) at Trinity College. Since learning how to create interactive urban history maps, he spends less time talking with his hands. (Photo by Andy Hart)_
