## Teaching with Oral History {-}

*Inspired by a conversation with Pamela Grundy, Jake Hardesty, and Kevin Zayed at the History of Education Society meeting in November 2018.*

How can we deepen student learning in our history classes by incorporating oral history interviewing and writing?

Two pedagogical models (and maybe more):
- Individual interviews to compare with traditional sources: describe, and goal is for students to write a conventional historical research paper, and to compare and contrast one oral interview transcript with traditional print sources
- Shared interviews for comparative analysis: describe, and goal is for an entire class of students to focus on a similar group of interview participants (or different groups who share a common experience), agree on common interview guide. Everyone conducts an interview and then share the transcripts into a common digital folder (via Google Drive or Dropbox or similar), so that small groups can compare & contrast interviews that have some commonalities or differences

Teaching students how to prepare and interview

Previously I searched for the "best oral history" article or chapter to assign to my students, thinking that knowledge would help them become better interviewers. But I now believe that interviewing is best taught as *experiential* learning, where students engage in the process and reflect on their successes and mistakes.

- the best interviewers are the best listeners, not the best talkers
- Read a sample interview transcript (and recording): In what portions did the interviewer do well, and how? Where could the interviewer have improved? Point out places where participants were encouraged to elaborate or redirected to the core question, or interrupted, allowed to ramble -- include CSS samples
- Think carefully about how and why you are selecting interview participants. There is nothing wrong with a selected sample or even a snowball sample, as long as you recognize and write out limitations.
- Read up on the people you're interviewing...
- Craft a common interview guide. Closed-ended survey-style questions versus open-ended questions that encourage participants to tell stories. Inserting prompts: "tell me more about..." and "how did you feel?" (not just how did you think or do) -- include CSS samples
The Debs-Dougherty interviewing principles. -- include CSS samples
- Conduct a practice interview with a friendly dual-role participant: who is a member of the community we wish to study, but also a member or understands our academic community. Schedule this for at least 30 minutes in class, and divide the time evenly between the "practice interview" and the "talk-back and reflection." The first half is a mock interview, with the recorder running, and assign several students to ask interview questions, in sequential order, using the class interview guide. In the second half, the participant shares what they believe worked well during the interview, and what could have been improved. For example, did students inappropriately interrupt? Did they ask about words or terms that they did not understand? Did they follow up on appropriate topics? Did they encourage storytelling and expression of feelings? Even if only three students conduct the mock interview, the entire class of students will learn by observing closely and imagining what they would -- or would not - have done in their classmates' shoes.

How to design consent forms and collaborate with repositories

How to transcribe

How to analyze and write history with oral interviews

Here's where reading helps greatly, compared to the experience of interviewing


See also JAH 1999 article on analyzing History
- Read sample body paragraphs ... even write some fake ones for your students....

Overall, start small -- teaching with oral history will become much easier the second and third time, when you will have sample interview guides, transcripts, and essays to share with future classes
