## REVISING -- Expanding Exclusionary Zoning {- #expanding-exclusionary-zoning}


In Hartford’s suburbs, zoning also became effective means to distance the haves from the have-nots.

growth of exclusionary zoning in surrounding Hartford-area suburbs, and increase of minimum-land requirements to 1-2 acres (43,000 to 87,000 square feet) per single-family home, as they competed with each other to attract higher-income families during the 1950s+

Drafting local ordinances this way made zoning an exclusionary tool to restrict neighborhoods by wealth, and most likely to pump up high-end real estate sales. Unlike other tools developed around the same time (such as racially restrictive property covenants that prohibited non-white residents, and have since been outlawed by civil rights legislation), wealth-based zoning remains perfectly legal today. But it does nothing to promote the health and safety of the citizenry, as promised by the original intent of the state law.

TODO insert map at the top of this page to orient readers to towns mentioned in text; colored polygons for minimum-land requirement (as of 1954?), based on @avonPresentZoningFact1954


... map of TOWNS around Hartford, YEAR when they implemented zoning, and COLORED POLYGONS for minimum-land requirement;






Further outward, the farming community of Avon named its first committee (?) to study zoning plan in 1934 (19341022HC)
Avon started its zoning board in 1939, but did not implement a major zoning plan until 1954, to maintain low-density (ie. higher-income) single-family housing during the postwar baby boom.

Avon 1951 zoning map and others  [https://archives.library.wcsu.edu/cao/ctavfpl/mapcollection.xml](https://archives.library.wcsu.edu/cao/ctavfpl/mapcollection.xml)


Avon and adjacent town zoning comparison 1954 @avonPresentZoningFact1954

dominant size of min plot/family

Avon (East) = 87000 (2 acre)

Avon (West) = 30000

Farmington (West) = 20000

Farmington (Northeast) = 40000

West Hartford (east of Mt Road = 10,000 (AA)

Bloomfield (west) = 30000 (R30)

Simsbury = 25000

Canton = no zoning regs

 shows present zoning for Avon (amended Oct 19, 1951, and Fall 1953) and comparisons for adjacent towns:

Bloomfield, adopted March 15, 1950

Simsbury, adopted Nov 21, 1952

West Hartford, amended to Dec 3, 1951

Farmington, adopted April 27, 1950


TODO -- reconstruct sources for Case Study: Avon (analysis of Professor Anika Singh Lemar, Yale Law School) in @boggsYourFairShare2020

1948  15,000 sq ft minimum parcel

1951 rezoned area west of Farmington River to min 2 acre parcels

1953 rezoned area east of Farmington River to min 30,000 sq ft

1957 rezoned portions of eastern area to min 40,000 sq ft; anticipates possibility of apartments by conditional permit

by 1967 vast majority of Avon is zoned for 1 acre and 2 acre lots; discrete areas zoned for commercial and industrial


see NAACP Wethersfield Custis zoning dispute 1953 @HSP.pdf -- Hartford Studies collection notes about NAACP objection to Wethersfield zoning process with 1950s test case, which challenges racism, but accepts principle of zoning by property size and wealth exclusion --
find quote: West Hartford 1970s mayor says no racial discrimination; blacks and puerto ricans simply can't afford to live here


Why did zoning not happen earlier in these towns?
- zoning infringed on individual rights of residents to use property as they wish, a core principle in rural comm.
- but as rural towns experienced rapid real estate development, they adopted suburban governments that traded individual rights for group protection against threats of urban life, such as apartment buildings with lower-income outsiders to their community

Why did zoning matter?
- zoning is built into the environment; once zoned for single-family homes, and those are built out, hard to make change
- zoning by local government inherently protects the interests of current residents, not interests of the metro region or the state in providing affordable housing opportunities for all residents...

In contrast to overt discrimination, towns like Avon [and WH?] began to exercise more subtle means of exclusion and homogenization through legal tools of zoning, taxation, and services. According to Downs, "...all suburbs have one major advantage regarding cultural homogeneity that is not shared by larger cities: suburban residents can make use of legal machinery to maintain their homogeneity by excluding those who may change it. Of course, they cannot directly prevent any particular group from entering by passing discriminatory laws but they can set up and enforce specific standards regarding building quality, tax rates, the character of public services, and the nature of the school system. By raising these standards high enough, they can make it economically impossible for 'disrupting' elements to enter the area and dilute the homogeneity which they seek to establish" p315 (quoted in Ladd, Ideology in America), source: Anthony Downs, "Metropolitan Growth and Future Political Problems." Land Economics 37 (1961): 311-20.
