## REVISING -- Expanding Exclusionary Zoning {- #expanding-exclusionary-zoning}




growth of exclusionary zoning in surrounding Hartford-area suburbs, and increase of minimum-land requirements to 1-2 acres (43,000 to 87,000 square feet) per single-family home, as they competed with each other to attract higher-income families during the 1950s+

Drafting local ordinances this way made zoning an exclusionary tool to restrict neighborhoods by wealth, and most likely to pump up high-end real estate sales. Unlike other tools developed around the same time (such as racially restrictive property covenants that prohibited non-white residents, and have since been outlawed by civil rights legislation), wealth-based zoning remains perfectly legal today. But it does nothing to promote the health and safety of the citizenry, as promised by the original intent of the state law.

TODO insert map at the top of this page to orient readers to towns mentioned in text; colored polygons for minimum-land requirement (as of 1954?), based on @avonPresentZoningFact1954


... map of TOWNS around Hartford, YEAR when they implemented zoning, and COLORED POLYGONS for minimum-land requirement;


## Bloomfield
trolley line to Center built by Italian laborers and finally opened 1909, with major celebration p90 opening of original 13-stanza poem by Chandler Miller, titled: ON to bloomfield, the Suburbs in the Hills On to bloomfield has, for many a year, Been the cry, till now the trolley is here On to Bloomfield, with its vales and its rills On to Bloomfield, the suburb in the hills "The banquet in the town hall was followed by speeches which revealed some ambivalence, looking at both good and bad features of the 'invasion of the first electric car.' Optimists believed thet people would leave the 'unhealthful tenements' for the good air of the country, only a ten cent fare away from the city. Real estate would boom and there would be a growth in population as new one-family hosues were built. Fear was also expressed, that local businesses would lose out as residents used the trolley to go to Hartford to shop." p92 Trolley line increased Italian immigration into Bloomfield's East Side in 1920
dedication of new state highway, Rt 189, through center after WWI, with quickened pace of life from auto (development spurred by war) "Increasingly, Bloomfield became a commuter town, as larger numbers of people looked to Hartford for employment, many of them in the insurance companies." p103
"In the late 1920s, efforts wer made to entice urban residents to Bloomfield. The town was given wide publicity as an attractive suburb of Hartford. In 1928..the town boasted of its residential character - no manufacturing. Emphasis was on fine estates and homes, 'plush' growth, and belief that 'land values will rise by leaps and bounds'.... The Blue Hills area, adjacent to Hartford, was described as 'removed from the center' a section of houses of the 'bungalow' type. Water lines were being laid, a high school site had been purchased, and the town had hired a professional to draw up a zoning plan. The zoning regulations, adopted in 1929, are an example of far-sighted vision and planning. Crucial to its plans was the location of the proposed state highway through town [Rt 189 dedicated in 1935] Its continuation from West Hartford thorugh the center of Bloomfield was vital in bringing to Bloomfield the kind of growth that had been sought." p107 [by whom?] "Despite the Depression, the 1937 Town Report noted that more new residences were under construction than at any previous time in the town's history." p107 the post-WWII pop boom "might have left Bloomfield only a 'bedroom' town. Visionary thinking and intense efforts to locate industry here overcame that eventuality. Growth in numbers of schoolage children by 1944 required a new school, a story repeated several times over the next decades." 1947 disc of housing developments; industrial zone set aside 1948 demand for recreational services since "Suburbia suffered from a lack of cultural and recreational opportunities readily available in cities." p110

Bloomfield became one of Connecticut's first towns to create a Planning Commission in 1917, which supervised the layout or new roads and housing subdivisions p193
Bloomfield created a Zoning Commission in 1926 WHS p193

Bloomfield voted to form Zoning Commission in Aug 1926
Zoning has been topic for past two years; several years ago Blue Hills land developed by real estate promoters "As a consequence, all kinds and classes of houses were built"
@WillVoteZoning1926; @ZoneCommissionFive1926
April 1927 The town of Bloomfield has created a zoning commission in order to get a comprehensive town plan and zoning ordinance. In accordance with a vote of the town, it has engaged Herbert S. Swan of New York as expert.
@ZoningProblemsBe1927

Nov 1927
The zoning committee of the town held a meeting at the town building Wednesday evening at which Herbert Swan, zoning expert, outlined the zoning regulations which are being drafted and also submitted a layout of Roberts Park. Mr. Swan is to prepare a survey in detail of his proposed layout of Roberts Park.
@BloomfieldZoningCommittee1927

June 1928 Bloomfield's Popularity As City's New Suburb Gains Hold in Hartford
real estate development opportunity article, which emphasizes large estates on Bloomfield Avenue and elsewhere; recent decision to install water mains to replace individual water wells;
current Bloomfield High School occupies 2nd floor of Jerome Ave grammar school, with plan to build a 400-student high school building soon, pending bond issue
Herbert Swan city planner is currently working on zoning plan for future growth of town
Blue Hills section is a "community of thrifty home owners" but most are "bungalow type" so not expected to match quality of residential construction on Bloomfield Ave
@BloomfieldPopularityCity1928

"The eyes of real estate men and those seeking homes in a suburb near a large city are turning to Bloomfield, which holds a unique position in Connecticut in that it is a strictly residential town and has no manufacturing whatever."
$2M in building permits (but mostly St Thomas Seminary)
about 900 enrolled in school; 5 percent gain per year
Blue Hills section expanded and six-room addition added to school, to make 14 rooms; also purchased 7 acres for high school site
recent creation of zoning commission with NYC expert Herbert Swan
@BloomfieldBuildingProgram1928

1928 Bloomfield Town Plan by Herbert Swan
Bloomfield will always be "a residence suburb" because "people who come to live in town must find their livelihood in Hartford" and the town must accept this fact, p.1
Hartford residential areas are almost completely built up, wth few vacant lots, so needs to capitalize on its location to widening urban community; with intellgient growth "its character will become progressively more distinctive and distinguishable from neighboring suburbs" p2
"The growth of Bloomfield will always depend to an exceptional degree upon its relationship to Hartford. The more intimately it can develop its plan with that of Hartford, the more growth Bloomfield will enjoy, as the growing suburan population of Hartford will undoubtedly seek out residence localities which, other things being equal, will be as near in the matter of time distance as possible to the business district of Hartford" p5
prepare major thoroughfare from Hartford to Bloomfield: lists 13 connector streets, some to be widened, p6
Land subdivisions: so far, very small proportion of land has been subdivided, but "very little good" can be said of current subdivisions, with max lots for developers but no major/minor streets and connecting roads, p. 18
"The zoning regulations in Bloomfield demand...." [unclear if they already exist, or should exist; probably the latter]
A zone = min land 5000 sq ft per family, 50 foot width (but town should demand 6250 sq ft), p19-20
(later B zone is mentioned, but no min land req given here)

Zoning proposed April 1929
Bloomfield Zoning Commission will hold public hearing April 8th on proposed zoning ordinance; "The proposed ordinance and maps defining the zoning districts will be on file for inspection... at the Town Building"
@BloomfieldProposedZoning1929

Zoning enforced 1929 - Bloomfield's new zoning laws, which became operative on April 12, 1929, are receiving their first court test by virtue of an action brought by the town against Josephine De Costin of Bloomfield, who is seeking to erect a gasoline station on West Street, a state highway, which runs through a residential area
Judge granted injunction to stop gas station @BloomfieldActionDecide1929

Bloomfield did not shy away from affordable multi-family housing in 1942
Within the next week the Bloomfield Town Plan and Zoning Commission will hold a public hearing on the application of the Harry L. Osias Realty Company of Brooklyn, N. Y., to develop a tract of land off Blue Hills Avenue and construct about 120 duplex-type houses... each unit would house two families, each of whom would hold title to the side in which it lived"
each duplex lot would be about 11k sq ft, meaning 5.5k per family; if granted, will become "D" residential zone; already has city sewers and water
@HearingPlannedProposal1942

1955 zoning plan revised
MDC is just beginning to install new sanitary sewers and water mains in heavily populated Bloomfield Center; "no large subdivisions will be encouraged in areas not served by MDC sewer and water systems" so western town dev will wait
about 90% of Bloomfield is zoned for residence: R10, R15, R20, R30, R40 combined; town zoning ordinances revised in 1955 with retired MIT Prof Flavel Shurtleff; new General Life Insurance Co building raised grand list; more fiscal details, school projections
@jensonBloomfield10YearChallenge1956

## Wethersfield not as restrictive
TODO: compare Whitten/West Hartford exclusionary strategy with less-divisive plan from Wethersfield 1928 by Swan, which had less restrictive zoning
Also note how anti-tenement view is expresed as public health benefit
schools section refers to Wethersfield zoning areas already adopted:
A at 9 families per acre
B at 18 families per acre
for calculating projected school enrollment, it uses A and shows lack of space in future
Zoning section describes how zoning cannot do everything (prevent shacks; aesthetic issues)...
@swanPlanResidenceSuburb1928




## East Hartford
In other suburban towns, residents strongly opposed zoning laws. At an East Hartford public meeting in 1927, all but two of the 75 present spoke against town zoning ordinance, seeking to repeal it.  Goerge Goodwin, a member of the EH zoning commission, acknowedged that zoning laws “were enacted whiel some misunderstood them. Many have told me that the zoning code was adopted here 10 or 15 years too late; that the laws are being enforced too late and after the damage has been done.”  A resident of West Hartford, who attended on behalf of a local resident, explained that zoning in his town had [indirect quote] “been the cause of an inordinate assessment and lax levy on certain land here” which caused some property owners to sell at a loss and leave town due to what they viewed as unreasonable property taxes.  -- 19270901HC EH opposition to zoning

## Hartford
By contrast, in the City of Hartford, retroactively zoning residential, commercial, and industrial development  would be extremely difficult and unwise, says expert; 19251213HC


## Windsor becoming more concerned in 1955
In drafting the proposed new zoning ordinance, the Plan and Zoning Commission continued to work with the problem of population density. Potential growth of the town was a major consideration in the preparation of the Comprehensive Town Plan.
new classifications:
R31 (31,250)
R20
R11 (11,250)
last winter's discussion of town plan "it was pointed out that uncontrolled gorwth of residential neighborhoods would send tax rates up. Schools, police and fire protection must follow the homes"
goal of encouraging "building of high quality small homes"
current zoning law requires larger homes in A than B or C zones "does not eet the requirements of small families with means to build a more expensive home",
allows convesion of 1-family to muti-family if lot is sufficiently large
@WindsorZoneLaw1955

## Avon
Further outward, the farming community of Avon named its first committee to study zoning in 1934; selectmen appoint cmte "to make a study of zoning systems in other towns with a view to institutiong a zoning system in the Town of Avon"
@AvonNamesCommittee1934

town meeting votes 150-59 to repeal zoning commission (established 28 Aug 1935) and zoning ordinances (created 2 Oct 1936); commisioner says due to "misundertanding on the part of some persons in the town who thought they were being deprived of their rights"
@ZoningOrdinancesAre1936

Avon town leaders tried a second time by appointing a zoning board in March 31, 1939 @mackieAvonConnecticutHistorical1988, p. 246

celebrates two years of zoning in Avon (since 1939); $300k increase in home building; 75 homes built in two years; Zoning Comission chief objective: "making sure that no 'gypsy camps' get started in the town, that no careless, hurried, shack-like building goes on to pull down the value of surrounding property"
thoughts about improving school facilities
Zoning Comm "set lot minimums at 100 x 150 feet" = 15,000 sq feet (1/3 acre)
@AvonReapsBenefits1941

With the encouragement of wealthy property owners, Avon town leaders enforced their zoning laws.
Photo with subtitle "Cabin among Mansions of Avon Doomed"
three-room cabin ordered demolished because not up to the standards of nearby estates; "not in character with the other residence in the neighborhood" that cost $25-50k
owner Lester Scheide is architect in Hartford
@ScheideBowAvon1940


Avon 1951 zoning map
West side = Residence & Ag Zone, min lot area 15k sq ft, min frontage 100 ft
East side = Residence Zone "A", min lot area 2 acres, min lot frontage 200 ft
@hodgeTownAvonZoning1951

October 1953
Court of Common Pleas ruled that Zoning Board made "illegal, artibrary" decision to set min lot sizes at 30k sq ft more than a year ago, so zoning reg will revert to original 15k sq ft
@CourtDecidesPlaintiffs1953

Nov 1953
Legal voters of the town of Avon at a special town meeting in Towed unanimously in favor of amendments to the zoning regulations adopted by the Zoning Commission.
East side of town - min lot of 2 acres and 200 ft frontage (in most cases)
West side of town = min lot of 30,000 sq ft (2/3 acre) and 150 ft frontage (in most cases)
@VotersApproveAmendments1953

Avon "General Plan of Development" adopted in 18 Dec 1954, based on work started in Dec 1952 guide to Zoning Commission, and consultant Joseph Moschner named in Dec 1953
@mackieAvonConnecticutHistorical1988, pp. 253-256

Avon was previously agricultural, but now residents are "lawyers, teachers, and insurance workers of Hartford; the skilled shop workers, electricians and engineers of East Hartford, New Britain and West Hartford"; 75% of Avon's workforce employed outside of town; Town planning consultant Dr Joseph Moschner says Avon area "generally attracts people in the higher income brackets people building expensive homes with large, well-landscaped lots"; Movement from Hartford, to West Hartford, to Avon. Moschner says "Avon may very well become the West Hartford of West Hartford"
@mackieAvonGrowsLiving1956

Conflicts between long-term residents and newcomers from the city were common. During a meeting of the Avon Zoning Commission in the mid-1940s, the presiding commissioner was repeatedly interrupted by a new resident. "Where in hell did you come from anyway?" asked the exasperated zoning commissioner. "West Hartford," replied the new resident. "Then why don't you do us a favor and go back there?" the zoning commissioner suggested.^[Oliver M. Thompson interview, Avon Historical Society, cited in @mackieAvonConnecticutHistorical1988, p. 254]

1964 Revised Zoning Map
originally Sept 1958, with multiple revisions
East side = mostly RU-2A rural zones (undefined on map)
West side = mixture of R-40, R-30, R-15, Business, Industrial, etc.
@technicalplanningassociatesAvonRevisedZoning1964

TODO -- reconstruct sources for Case Study: Avon (analysis of Professor Anika Singh Lemar, Yale Law School) in @boggsYourFairShare2020

1948  15,000 sq ft minimum parcel

1951 rezoned area west of Farmington River to min 2 acre parcels

1953 rezoned area east of Farmington River to min 30,000 sq ft

1957 rezoned portions of eastern area to min 40,000 sq ft; anticipates possibility of apartments by conditional permit

by 1967 vast majority of Avon is zoned for 1 acre and 2 acre lots; discrete areas zoned for commercial and industrial


## Minimum Land Required Per Family by Town Zoning in early 1950s

| Town (section)         | Square Ft | Acres |
|:-----------------------|----------:|------:|
| Avon (east)            | 87,000    | 2.0   |
| Avon (west)            | 30,000    | 0.7   |
| Farmington (northeast) | 40,000    | 0.9   |
| Farmington (west)      | 20,000    | 0.5   |
| Bloomfield (west)      | 30,000    | 0.7   |
| Simsbury               | 25,000    | 0.6   |
| West Hartford (west)   | 10,000    | 0.2   |
| Burlington             | not zoned | n/a   |
| Canton                 | not zoned | n/a   |

Sources: Zoning Regulations for Avon (amended Oct 19, 1951, and Fall 1953); Bloomfield (adopted March 15, 1950); Simsbury (adopted Nov 21, 1952); West Hartford (amended to Dec 3, 1951); Farmington (adopted April 27, 1950), adapted from Avon and Joseph Moschner, “Present Zoning Fact Sheet [Map]” (Avon Town Planning Committee, Connecticut, January 1954), https://www.avonct.gov/planning-community-development/files/1956-pocd-maps-908.
@avonPresentZoningFact1954




## Wethersfield and Custis NAACP case

see NAACP Wethersfield Custis zoning dispute 1953 @HSP.pdf -- Hartford Studies collection notes about NAACP objection to Wethersfield zoning process with 1950s test case, which challenges racism, but accepts principle of zoning by property size and wealth exclusion --

## West Hartford expansion

1933 WH added new classifications "for the protection of large homes requiring more area"
AAA single houses, min land 18000 sq ft, lot width 100 ft
AA single houses, min land 12000 sq ft, lot width 80 ft
@westhartfordReportZoningCommission1934, p. 119

town approved new zoning regs Aug 6th 1945 as the "first revision of the regulations since the inception of zoning in 1924"; new map shown publicly and approval expected in spring 1946; all E changed to D; creation of Business 1 zones
@westhartfordReportZoningCommission1946, pp. 48-49

WH town council adopts new zoning May 6, 1946, expanding A-E range to AAA, AA, A, B, C, D, G residence district; revisions on map up to 1951 shows changes from 1930 such as:
much of the B-grade land in southwest area (Wood Pond) has been shifted to A-grade
most of north and northwest section has shifted from A to AA grade
most of area west of Bishop’s Corners shifted from B grade to AA grade
area around Hartford golf club shifted from B grade to AA grade
see decreasing or degrading residential area on southeast side, bordering Hartford
TO DO: look for HC or WHN articles around May 6 1946

1968
"Better Neighborhoods Through...
Enforcement of Housing Codes and Zoning Regulations"
"Good neighborhoods in the Town will remain through the continued upgrading by your Town goverment of the residential zoning of some 22,121 residential units and the enforcement of housing codes, which protect the appearance and value of residential property"
@westhartfordAnnualReportTown1968, no page numbers



## West Hartford 1970s
find quote: West Hartford 1970s mayor says no racial discrimination; blacks and puerto ricans simply can't afford to live here


Why did zoning not happen earlier in these towns?
- zoning infringed on individual rights of residents to use property as they wish, a core principle in rural comm.
- but as rural towns experienced rapid real estate development, they adopted suburban governments that traded individual rights for group protection against threats of urban life, such as apartment buildings with lower-income outsiders to their community

Why did zoning matter?
- zoning is built into the environment; once zoned for single-family homes, and those are built out, hard to make change
- zoning by local government inherently protects the interests of current residents, not interests of the metro region or the state in providing affordable housing opportunities for all residents...

In contrast to overt discrimination, towns like Avon [and WH?] began to exercise more subtle means of exclusion and homogenization through legal tools of zoning, taxation, and services. According to Downs, "...all suburbs have one major advantage regarding cultural homogeneity that is not shared by larger cities: suburban residents can make use of legal machinery to maintain their homogeneity by excluding those who may change it. Of course, they cannot directly prevent any particular group from entering by passing discriminatory laws but they can set up and enforce specific standards regarding building quality, tax rates, the character of public services, and the nature of the school system. By raising these standards high enough, they can make it economically impossible for 'disrupting' elements to enter the area and dilute the homogeneity which they seek to establish" p315 (quoted in Ladd, Ideology in America), source: Anthony Downs, "Metropolitan Growth and Future Political Problems." Land Economics 37 (1961): 311-20.
