## Zoning Today {#zoning-today}

NOTES

Today in Connecticut, we continue to struggle with this legacy of our restrictive land-use laws. Exclusionary zoning has been criticized in multiple reports as a barrier to fair housing and equal opportunity.[@suburbanactioninstituteStudyZoningConnecticut1978; @reecePeoplePlaceOpportunity2009] In 2013, the Connecticut Fair Housing Center and Trinity College student researcher Fionnuala Darby-Hudgens and I compiled all of the local zoning ordinances for towns across Connecticut and evaluated them on their degree of restrictions against affordable housing for the Connecticut Zoning Initiative.[@connecticutfairhousingcenterConnecticutZoningInitiative2013; @connecticutfairhousingcenterGuideZoningFair2013; @connecticutfairhousingcenterAnalysisImpedimentsFair2015]

### Explore Connecticut Zoning Initiative maps and data {-}

TODO: Coming soon -- Residential Zoning Analysis by CT Fair Housing Center <https://fionnualadh.github.io/cfhc-residential-zoning-analysis/> to replace older version <http://commons.trincoll.edu/cssp/zoning>

Exclusionary zoning across 169 Connecticut towns, 2012:

- 23 prohibit new construction of multi-family housing (red)
- 122 require special permit for multi-family housing (yellow)
- 13 require > 2 acre lot size for single-family homes
- 18 require > 5 acre lot size for multi-family homes

TO DO: review slides and transform into text <https://docs.google.com/presentation/d/1yYDQTzNoUBzCW6tCSH21beUrwsYQVwVTQO3Ctqf2BPM/edit#slide=id.g299a37f04f_0_0>

But these zoning analysis maps are incomplete because there is no uniform reporting requirements for local zoning ordinances, and no state entity charged with collecting this data in meaningful ways. Despite these obstacles, the question remains the same. If we wish to keep zoning as a governmental policy to regulate market forces in real estate, what kind of tool do we want it to be? Should we consider rewriting exclusionary zoning laws to make them more helpful for the health of our communities?
