## Teaching Oral History {-}

*DRAFT outline of chapter to come by Jack Dougherty*

 In this presentation, Jack Dougherty will offer both philosophical and pragmatic strategies for teaching students to plan, conduct, transcribe, analyze, and publish oral history interviews about race and education. Several guides to oral history emphasize the logistics and legalities of collecting and curating interviews, primarily for directors of oral history centers, archivists, and scholars. But few emphasize the pedagogical skills of teaching students how to create and interpret oral histories, particularly in the the context of a college-level course. Specific strategies in this session will include: designing individual versus comparative oral history assignments; crafting interview questions about race, perspective, and power; conducting group practice interviews with selected participants who also provide feedback to improve the process; designing consent forms that address the ethics of ownership and copyright; guidelines to improve the transcribing process; teaching students to shift from anecdotes to analysis in writing about oral history. The presentation will feature examples of oral history interviews on race, education, and reform from More Than One Struggle on Milwaukee WI and On The Line on Hartford CT.

 See HES 2019 panel proposal, Oral History and African American Educational History
 https://docs.google.com/document/d/1-BUopM6OYEkfuZ1S5p2nixU9iD5qBkL41LPdpO-rUsQ/edit

How can we deepen student learning in our history classes by incorporating oral history interviewing and writing?

Most publications about oral history emphasize logistics and legalities of collecting, curating, and disseminating, primarily for directors of oral history centers, archivists, and scholars. Cite: Oral History Association published its “Principles and Best Practices” document in 2009, but it’s mostly about logistical and ethical issues, not analysis
http://www.oralhistory.org/about/principles-and-practices/
Troy Reeves is leading the current rewrite of these for 2018, which you can see in Google Docs format here:
https://drive.google.com/drive/folders/1t1-UOGVFGhqXVpkpVRpN5mj8ORvSxKbM
Doug Boyd edited this open-access volume of essays on Oral History in the Digital Age in 2012, which mostly features essays on collecting, curating, and disseminating.
http://www.oralhistory.org/oral-history-in-the-digital-age/

But fewer authors emphasize how to teach oral history, particularly in the context of a college-level history course.

Two pedagogical models (and maybe more):
- Individual interviews to compare with traditional sources: describe, and goal is for students to write a conventional historical research paper, and to compare and contrast one oral interview transcript with traditional print sources
- Shared interviews for comparative analysis: describe, and goal is for an entire class of students to focus on a similar group of interview participants (or different groups who share a common experience), agree on common interview guide. Everyone conducts an interview and then share the transcripts into a common digital folder (via Google Drive or Dropbox or similar), so that small groups can compare & contrast interviews that have some commonalities or differences

Teaching students how to prepare and interview

Previously I searched for the "best oral history" article or chapter to assign to my students, thinking that knowledge would help them become better interviewers. But I now believe that interviewing is best taught as *experiential* learning, where students engage in the process and reflect on their successes and mistakes.

- the best interviewers are the best listeners, not the best talkers
- Read a sample interview transcript (and recording): In what portions did the interviewer do well, and how? Where could the interviewer have improved? Point out places where participants were encouraged to elaborate or redirected to the core question, or interrupted, allowed to ramble -- include CSS samples
- Think carefully about how and why you are selecting interview participants. There is nothing wrong with a selected sample or even a snowball sample, as long as you recognize and write out limitations.
- Read up on the people you're interviewing...
- Craft a common interview guide. Closed-ended survey-style questions versus open-ended questions that encourage participants to tell stories. Inserting prompts: "tell me more about..." and "how did you feel?" (not just how did you think or do) -- include CSS samples
The Debs-Dougherty interviewing principles. -- include CSS samples
- Conduct a practice interview with a friendly dual-role participant: who is a member of the community we wish to study, but also a member or understands our academic community. Schedule this for at least 30 minutes in class, and divide the time evenly between the "practice interview" and the "talk-back and reflection." The first half is a mock interview, with the recorder running, and assign several students to ask interview questions, in sequential order, using the class interview guide. In the second half, the participant shares what they believe worked well during the interview, and what could have been improved. For example, did students inappropriately interrupt? Did they ask about words or terms that they did not understand? Did they follow up on appropriate topics? Did they encourage storytelling and expression of feelings? Even if only three students conduct the mock interview, the entire class of students will learn by observing closely and imagining what they would -- or would not - have done in their classmates' shoes.

How to design consent forms and collaborate with repositories

- Jack Dougherty and Candace Simpson, “Who Owns Oral History? A Creative Commons Solution,” in Oral History in the Digital Age, ed. Doug Boyd et al. (Washington, DC: Institute of Library and Museum Services, 2012), http://ohda.matrix.msu.edu/2012/06/a-creative-commons-solution/.
(which has broken links in this version, and I need to update it in On The Line).

How to transcribe
- see the latter portion of this essay, one of the most popular I've ever written on the web https://commons.trincoll.edu/jackdougherty/how-to/record-and-transcribe/

How to analyze and write history with oral interviews

- Here's where reading helps greatly, compared to the experience of interviewing

- Review key concepts from Jack Dougherty, “From Anecdote to Analysis: Oral Interviews and New Scholarship in Educational History,” The Journal of American History 86, no. 2 (1999): 712–23, http://www.jstor.org/stable/2567055.

- Read sample body paragraphs ... even write some fake ones for your students....



Overall, start small -- teaching with oral history will become much easier the second and third time, when you will have sample interview guides, transcripts, and essays to share with future classes


*Inspired by a conversation with Pamela Grundy, Jake Hardesty, and Kevin Zayed at the History of Education Society meeting in November 2018.*

OLD NOTES to review

Good to hear from you (and also that you survived your first year at Trinity and are full of energy with plans for the next one!)

Sounds like you already have a clear sense of what you wish to accomplish with oral history interviewing with adult immigrants for the community-learning component of this thoughtful course essay. Making meaningful connections between real-world community experience and theoretically-driven course content is usually the hardest challenge for students (and faculty), so you're more than halfway there.

Some random thoughts and resources:

1) Ethical interviewing practices
Whether or not "individualized" oral history interviews are subject to IRB review has been debated for the past decade. Sidenote: The Oral History Association has made the case that individualized interviews are not "research," which social science & federal authorities often define as something like "universal knowledge about human behavior." Go figure. So you need to decide whether or not you wish your students to do IRB review and training for this. If you go that route, then see examples on this page:
http://commons.trincoll.edu/jackdougherty/2012/09/27/irb/
But even if you choose not to do IRB review for the class project, oral historians still contend that there are ethical obligations for participants to voluntarily consent and know what will become of their interview recordings and transcripts, particularly with vulnerable populations. You may find this essay (and link to sample consent forms) helpful:
http://ohda.matrix.msu.edu/2012/06/a-creative-commons-solution/

2) Interview prep
By far the best strategy I've found for working with students to prepare for CLI interviewing is to:
- have them prepare a uniform interview guide (focusing on a select number of essential questions, rather than a long list of questions)
- invite a guest who has a foot in both worlds (Trinity and the Hartford community we're studying) to do a "practice interview" in class
- immediately after the practice interview, ask the guest to tell the class what worked and what needs improvement with their interview process
- ask the class to reflect on lessons learned and revise the interview guide
I used to search for the "best" readings in oral history, and finally decided that my students learned so much more via this experiential approach, if I have a guest who is willing to participate and understands why it's important. Homayra Ziad in Religion has had similar positive experiences with this approach.

3) Digital recording logistics -- this is much easier than it used to be
http://commons.trincoll.edu/jackdougherty/2013/04/09/digital-recorder/

4) Transcribing digital sound recordings
Haven't written a post on this yet, but I tell my students to download a free trial version of InqScribe, and to paste output directly into their favorite word processor. But there are other free tools.

5) Analyzing interviews for class writing assignments
You already have a perfectly fine 1-to-1 model to pair each Trinity student with an adult immigrant, and to write about whether theories in class correspond with the immigrant's experience. But since you're so far ahead of the game (it's only June 6th), I would encourage you to consider an alternative 1-to-2 model that may help students to write richer papers, perhaps like this:

- each Trinity student conducts 1 interview and uploads his/her transcript to a shared digital space (Moodle, Dropbox, whatever)
- for the essay, require each student to select any 2 interviews and compare/contrast how theoretical concepts apply (or not) each each case.

If you go this route, then you also need to make sure that students are "scrubbing" their interview transcripts to remove any personally identifying information before uploading to the digital shared space. Also, comparing two interviews is more like "research" that's subject to IRB review than the 1-to-1 individualized approach.

hope that helps -- if you want to discuss any of the above, I'm happy to sit down with you during late afternoons (3-4pm), just suggest possible dates

Jack
