## Teaching with Oral History {-}

*DRAFT outline of chapter to come by Jack Dougherty*

 In this presentation, Jack Dougherty will offer both philosophical and pragmatic strategies for teaching students to plan, conduct, transcribe, analyze, and publish oral history interviews about race and education. Several guides to oral history emphasize the logistics and legalities of collecting and curating interviews, primarily for directors of oral history centers, archivists, and scholars. But few emphasize the pedagogical skills of teaching students how to create and interpret oral histories, particularly in the the context of a college-level course. Specific strategies in this session will include: designing individual versus comparative oral history assignments; crafting interview questions about race, perspective, and power; conducting group practice interviews with selected participants who also provide feedback to improve the process; designing consent forms that address the ethics of ownership and copyright; guidelines to improve the transcribing process; teaching students to shift from anecdotes to analysis in writing about oral history. The presentation will feature examples of oral history interviews on race, education, and reform from More Than One Struggle on Milwaukee WI and On The Line on Hartford CT.

How can we deepen student learning in our history classes by incorporating oral history interviewing and writing?

Most publications about oral history emphasize logistics and legalities of collecting, curating, and disseminating, primarily for directors of oral history centers, archivists, and scholars. Cite: Oral History Association published its “Principles and Best Practices” document in 2009, but it’s mostly about logistical and ethical issues, not analysis
http://www.oralhistory.org/about/principles-and-practices/
Troy Reeves is leading the current rewrite of these for 2018, which you can see in Google Docs format here:
https://drive.google.com/drive/folders/1t1-UOGVFGhqXVpkpVRpN5mj8ORvSxKbM
Doug Boyd edited this open-access volume of essays on Oral History in the Digital Age in 2012, which mostly features essays on collecting, curating, and disseminating.
http://www.oralhistory.org/oral-history-in-the-digital-age/

But fewer authors emphasize how to teach oral history, particularly in the context of a college-level history course.

Two pedagogical models (and maybe more):
- Individual interviews to compare with traditional sources: describe, and goal is for students to write a conventional historical research paper, and to compare and contrast one oral interview transcript with traditional print sources
- Shared interviews for comparative analysis: describe, and goal is for an entire class of students to focus on a similar group of interview participants (or different groups who share a common experience), agree on common interview guide. Everyone conducts an interview and then share the transcripts into a common digital folder (via Google Drive or Dropbox or similar), so that small groups can compare & contrast interviews that have some commonalities or differences

Teaching students how to prepare and interview

Previously I searched for the "best oral history" article or chapter to assign to my students, thinking that knowledge would help them become better interviewers. But I now believe that interviewing is best taught as *experiential* learning, where students engage in the process and reflect on their successes and mistakes.

- the best interviewers are the best listeners, not the best talkers
- Read a sample interview transcript (and recording): In what portions did the interviewer do well, and how? Where could the interviewer have improved? Point out places where participants were encouraged to elaborate or redirected to the core question, or interrupted, allowed to ramble -- include CSS samples
- Think carefully about how and why you are selecting interview participants. There is nothing wrong with a selected sample or even a snowball sample, as long as you recognize and write out limitations.
- Read up on the people you're interviewing...
- Craft a common interview guide. Closed-ended survey-style questions versus open-ended questions that encourage participants to tell stories. Inserting prompts: "tell me more about..." and "how did you feel?" (not just how did you think or do) -- include CSS samples
The Debs-Dougherty interviewing principles. -- include CSS samples
- Conduct a practice interview with a friendly dual-role participant: who is a member of the community we wish to study, but also a member or understands our academic community. Schedule this for at least 30 minutes in class, and divide the time evenly between the "practice interview" and the "talk-back and reflection." The first half is a mock interview, with the recorder running, and assign several students to ask interview questions, in sequential order, using the class interview guide. In the second half, the participant shares what they believe worked well during the interview, and what could have been improved. For example, did students inappropriately interrupt? Did they ask about words or terms that they did not understand? Did they follow up on appropriate topics? Did they encourage storytelling and expression of feelings? Even if only three students conduct the mock interview, the entire class of students will learn by observing closely and imagining what they would -- or would not - have done in their classmates' shoes.

How to design consent forms and collaborate with repositories

- Jack Dougherty and Candace Simpson, “Who Owns Oral History? A Creative Commons Solution,” in Oral History in the Digital Age, ed. Doug Boyd et al. (Washington, DC: Institute of Library and Museum Services, 2012), http://ohda.matrix.msu.edu/2012/06/a-creative-commons-solution/.
(which has broken links in this version, and I need to update it in On The Line).

How to transcribe
- see the latter portion of this essay, one of the most popular I've ever written on the web https://commons.trincoll.edu/jackdougherty/how-to/record-and-transcribe/

How to analyze and write history with oral interviews

- Here's where reading helps greatly, compared to the experience of interviewing

- Review key concepts from Jack Dougherty, “From Anecdote to Analysis: Oral Interviews and New Scholarship in Educational History,” The Journal of American History 86, no. 2 (1999): 712–23, http://www.jstor.org/stable/2567055.

- Read sample body paragraphs ... even write some fake ones for your students....



Overall, start small -- teaching with oral history will become much easier the second and third time, when you will have sample interview guides, transcripts, and essays to share with future classes


*Inspired by a conversation with Pamela Grundy, Jake Hardesty, and Kevin Zayed at the History of Education Society meeting in November 2018.*
